Repository CESNET/perun-web-apps, pull requests merged in 2020-08, with the labels that each got.

#392 Devel info
  apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.html
  apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.scss
  apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.ts
  apps/admin-gui/src/assets/config/defaultConfig.json
Labels: waiting for review

#401 Vo invite members
  apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#371 Attributes value improvement
  apps/admin-gui/src/assets/i18n/en.json
  apps/admin-gui/src/styles.scss
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-boolean/attribute-value-boolean.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-boolean/attribute-value-boolean.component.ts
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-integer/attribute-value-integer.component.css
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-integer/attribute-value-integer.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-integer/attribute-value-integer.component.ts
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.scss
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.ts
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.scss
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.ts
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.scss
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.ts
  libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/components/src/lib/show-value-dialog/show-value-dialog.component.html
  libs/perun/components/src/lib/show-value-dialog/show-value-dialog.component.scss
  libs/perun/components/src/lib/show-value-dialog/show-value-dialog.component.spec.ts
  libs/perun/components/src/lib/show-value-dialog/show-value-dialog.component.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for rebase

#383 Copy empty application form - warning message
  apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#379 Member groups add/remove
  apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.spec.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/remove-member-group-dialog/remove-member-group-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/remove-member-group-dialog/remove-member-group-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/remove-member-group-dialog/remove-member-group-dialog.component.spec.ts
  apps/admin-gui/src/app/shared/components/dialogs/remove-member-group-dialog/remove-member-group-dialog.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/vos/components/member-group-list/member-group-list.component.html
  apps/admin-gui/src/app/vos/components/member-group-list/member-group-list.component.scss
  apps/admin-gui/src/app/vos/components/member-group-list/member-group-list.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts
  apps/admin-gui/src/app/vos/vos.module.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for rebase

#407 User profile - OAuth fix
  apps/user-profile/src/assets/config/defaultConfig.json
Labels: waiting for review

#388 Service detail
  apps/admin-gui/src/app/admin/admin-routing.module.ts
  apps/admin-gui/src/app/admin/admin.module.ts
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/admin-services.component.spec.ts
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/admin-services.component.ts
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.scss
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.ts
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-overview/service-overview.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-overview/service-overview.component.scss
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-overview/service-overview.component.ts
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-required-attributes/service-required-attributes.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-required-attributes/service-required-attributes.component.scss
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-required-attributes/service-required-attributes.component.ts
  apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-attributes/resource-settings-attributes.component.ts
  apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html
  apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.scss
  apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-required-attributes-dialog/add-required-attributes-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-required-attributes-dialog/add-required-attributes-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/add-required-attributes-dialog/add-required-attributes-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/create-edit-service-dialog/create-edit-service-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-edit-service-dialog/create-edit-service-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/create-edit-service-dialog/create-edit-service-dialog.component.spec.ts
  apps/admin-gui/src/app/shared/components/dialogs/create-edit-service-dialog/create-edit-service-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/create-service-dialog/create-service-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-service-dialog/create-service-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-definition-dialog/edit-attribute-definition-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/remove-required-attributes-dialog/remove-required-attributes-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/remove-required-attributes-dialog/remove-required-attributes-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/remove-required-attributes-dialog/remove-required-attributes-dialog.component.ts
  apps/admin-gui/src/app/shared/components/services-list/services-list.component.html
  apps/admin-gui/src/app/shared/components/services-list/services-list.component.scss
  apps/admin-gui/src/app/shared/components/services-list/services-list.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/assets/config/defaultConfig.json
  apps/admin-gui/src/assets/i18n/en.json
  apps/admin-gui/src/styles.scss
  libs/config/table-config/src/lib/table-config.service.ts
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.spec.ts
  package.json
Labels: waiting for review

#380 Groups changes
  apps/admin-gui/src/app/shared/components/debounce-filter/debounce-filter.component.html
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-relations/group-settings-relations.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts
  apps/admin-gui/src/app/vos/vos.module.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/edit-group-dialog/edit-group-dialog.component.html
  libs/perun/components/src/lib/edit-group-dialog/edit-group-dialog.component.scss
  libs/perun/components/src/lib/edit-group-dialog/edit-group-dialog.component.spec.ts
  libs/perun/components/src/lib/edit-group-dialog/edit-group-dialog.component.ts
  libs/perun/components/src/lib/group-menu/group-menu.component.html
  libs/perun/components/src/lib/group-menu/group-menu.component.scss
  libs/perun/components/src/lib/group-menu/group-menu.component.ts
  libs/perun/components/src/lib/group-sync-detail-dialog/group-sync-detail-dialog.component.html
  libs/perun/components/src/lib/group-sync-detail-dialog/group-sync-detail-dialog.component.scss
  libs/perun/components/src/lib/group-sync-detail-dialog/group-sync-detail-dialog.component.spec.ts
  libs/perun/components/src/lib/group-sync-detail-dialog/group-sync-detail-dialog.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/components/src/lib/groups-tree/groups-tree.component.html
  libs/perun/components/src/lib/groups-tree/groups-tree.component.scss
  libs/perun/components/src/lib/groups-tree/groups-tree.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/services/src/lib/gui-auth-resolver.service.ts
Labels: requested changes

#362 Resource assigned services page implemented
  apps/admin-gui/src/app/facilities/facilities-routing.module.ts
  apps/admin-gui/src/app/facilities/facilities.module.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.scss
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.spec.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.spec.ts
  apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/remove-service-from-resource-dialog/remove-service-from-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/remove-service-from-resource-dialog/remove-service-from-resource-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/remove-service-from-resource-dialog/remove-service-from-resource-dialog.component.spec.ts
  apps/admin-gui/src/app/shared/components/dialogs/remove-service-from-resource-dialog/remove-service-from-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/components/services-list/services-list.component.html
  apps/admin-gui/src/app/shared/components/services-list/services-list.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/assets/i18n/en.json
  apps/admin-gui/src/assets/img/PerunWebImages/service-white.svg
  libs/config/table-config/src/lib/table-config.service.ts
  libs/perun/services/src/lib/custom-icon.service.ts
  package-lock.json
Labels: waiting for rebase

#410 User profile - Breadcrumb update
  apps/admin-gui/src/assets/i18n/en.json
  apps/user-profile/src/app/app.component.html
  apps/user-profile/src/app/app.component.scss
  apps/user-profile/src/app/app.module.ts
  apps/user-profile/src/app/components/breadcrumbs/breadcrumbs.component.html
  apps/user-profile/src/app/components/breadcrumbs/breadcrumbs.component.scss
  apps/user-profile/src/app/components/breadcrumbs/breadcrumbs.component.spec.ts
  apps/user-profile/src/app/components/breadcrumbs/breadcrumbs.component.ts
  apps/user-profile/src/assets/i18n/cz.json
  apps/user-profile/src/assets/i18n/en.json
  libs/perun/components/src/lib/show-value-dialog/show-value-dialog.component.html
  package-lock.json
  package.json
Labels: waiting for review

#309 Facility management: Services status page
  apps/admin-gui/src/app/facilities/facilities-routing.module.ts
  apps/admin-gui/src/app/facilities/facilities.module.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.scss
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/config/table-config/src/lib/table-config.service.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/components/src/lib/services-status-list/services-status-list.component.css
  libs/perun/components/src/lib/services-status-list/services-status-list.component.html
  libs/perun/components/src/lib/services-status-list/services-status-list.component.ts
  libs/perun/openapi/src/lib/model/attributeDefinitionAllOf.ts
  libs/perun/pipes/src/index.ts
  libs/perun/pipes/src/lib/perun-pipes.module.ts
  libs/perun/pipes/src/lib/service-state-blocked-to-string.pipe.ts
  libs/perun/services/src/lib/custom-icon.service.ts
  package-lock.json
  package.json
Labels: requested changes

#412 Member expiration improvements
  apps/admin-gui/src/app/app.module.ts
  apps/admin-gui/src/app/shared/pipes/member-status-tooltip.pipe.ts
  apps/admin-gui/src/app/shared/pipes/transform-member-status.pipe.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/vos/components/members-list/members-list.component.html
  apps/admin-gui/src/app/vos/components/members-list/members-list.component.scss
  apps/admin-gui/src/app/vos/components/members-list/members-list.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.scss
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  apps/admin-gui/src/styles.scss
  libs/perun/components/src/index.ts
  libs/perun/components/src/lib/change-expiration-dialog/change-expiration-dialog.component.html
  libs/perun/components/src/lib/change-expiration-dialog/change-expiration-dialog.component.scss
  libs/perun/components/src/lib/change-expiration-dialog/change-expiration-dialog.component.spec.ts
  libs/perun/components/src/lib/change-expiration-dialog/change-expiration-dialog.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/urns/src/lib/perun-urns.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for review

#385 Issue 376: User - Identities
  apps/admin-gui/src/app/shared/components/user-detail-page/user-identities/user-identities.component.html
Labels: requested changes

#420 Header checkbox position fix
  apps/admin-gui/src/styles.scss
Labels: waiting for review

#372 Edits for facility, resource, vo, group implemented
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.spec.ts
  apps/admin-gui/src/app/shared/components/dialogs/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/openapi/src/lib/api/groupsManager.service.ts
Labels: waiting for review

#418 Authorization home section
  apps/admin-gui/src/app/shared/components/user-detail-page/user-dashboard/user-dashboard.component.ts
  apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-facility-attributes/user-settings-facility-attributes.component.ts
  libs/perun/components/src/lib/attributes-list/attributes-list.component.html
  libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
Labels: waiting for review

#431 Group list routing fix
  libs/perun/components/src/lib/group-menu/group-menu.component.html
  libs/perun/components/src/lib/group-menu/group-menu.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
Labels: waiting for review

#422 Authorization member section
  apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.scss
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-detail-page.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-resources/member-resources.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-resources/member-resources.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.ts
  apps/admin-gui/src/app/vos/vos-routing.module.ts
  apps/admin-gui/src/app/vos/vos.module.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/index.ts
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-integer/attribute-value-integer.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.html
  libs/perun/components/src/lib/attributes-list/attributes-list.component.html
  libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
Labels: waiting for review
