Repository CESNET/perun-web-apps, pull requests merged in 2020-09, with the labels that each got.

#424 Authorization Facility section
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-security-teams/facility-security-teams.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-security-teams/facility-security-teams.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-owners/facility-settings-owners.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-owners/facility-settings-owners.component.ts
  apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html
  apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.ts
  apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html
  apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts
  apps/admin-gui/src/app/shared/components/owners-list/owners-list.component.ts
  apps/admin-gui/src/app/shared/components/security-teams-list/security-teams-list.component.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.html
Labels: waiting for rebase

#426 Authorization - resource section
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-dialog/delete-attribute-dialog.component.ts
  apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts
  apps/admin-gui/src/app/shared/components/services-list/services-list.component.scss
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/app/vos/vos-routing.module.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.html
  libs/perun/components/src/lib/attributes-list/edit-attribute-dialog/edit-attribute-dialog.component.ts
Labels: waiting for review

#430 Move group bug fix
  apps/admin-gui/src/app/shared/components/dialogs/move-group-dialog/move-group-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/move-group-dialog/move-group-dialog.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/group-menu/group-menu.component.html
Labels: waiting for review

#432 Facility allowed users
  apps/admin-gui/src/app/facilities/facilities-routing.module.ts
  apps/admin-gui/src/app/facilities/facilities.module.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.scss
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-manager-dialog/add-manager-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/connect-identity/connect-identity.html
  apps/admin-gui/src/app/shared/components/users-list/users-list.component.html
  apps/admin-gui/src/app/shared/components/users-list/users-list.component.scss
  apps/admin-gui/src/app/shared/components/users-list/users-list.component.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/config/table-config/src/lib/table-config.service.ts
Labels: waiting for review

#421 Vo authorization
  apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/edit-email-footer-dialog/edit-email-footer-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-email-footer-dialog/edit-email-footer-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/move-group-dialog/move-group-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/move-group-dialog/move-group-dialog.component.ts
  apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html
  apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts
  apps/admin-gui/src/app/shared/components/resources-tags-list/resources-tags-list.component.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.html
  apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.ts
  apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.ts
  apps/admin-gui/src/app/vos/components/expiration-settings/expiration-settings.component.html
  apps/admin-gui/src/app/vos/components/members-list/members-list.component.html
  apps/admin-gui/src/app/vos/components/members-list/members-list.component.scss
  apps/admin-gui/src/app/vos/components/members-list/members-list.component.ts
  apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.html
  apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-attributes/vo-attributes.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-attributes/vo-attributes.component.scss
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-attributes/vo-attributes.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-overview/vo-resources-overview.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-preview/vo-resources-preview.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-preview/vo-resources-preview.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-tags/vo-resources-tags.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-tags/vo-resources-tags.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-extsources/vo-settings-extsources.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-extsources/vo-settings-extsources.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-overview/vo-settings-overview.component.ts
  apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.html
  apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts
  apps/admin-gui/src/app/vos/vos-routing.module.ts
  apps/admin-gui/src/app/vos/vos.module.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/index.ts
  libs/perun/components/src/lib/group-menu/group-menu.component.html
  libs/perun/components/src/lib/group-menu/group-menu.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/components/src/lib/groups-tree/groups-tree.component.html
  libs/perun/components/src/lib/groups-tree/groups-tree.component.ts
  libs/perun/models/src/lib/GroupFlatNode.ts
  libs/perun/models/src/lib/TreeGroup.ts
Labels: waiting for review

#442 Edit user
  apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.html
  apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/edit-user-dialog/edit-user-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-user-dialog/edit-user-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/edit-user-dialog/edit-user-dialog.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/openapi/src/lib/api/facilitiesManagerByFacilityName.service.ts
  libs/perun/openapi/src/lib/api/groupsManager.service.ts
  libs/perun/openapi/src/lib/api/tasksManager.service.ts
  libs/perun/openapi/src/lib/api/usersManager.service.ts
  libs/perun/openapi/src/lib/model/inputUpdateUser.ts
  libs/perun/openapi/src/lib/model/models.ts
  libs/perun/openapi/src/lib/model/taskAndDestinationIdObject.ts
  libs/perun/openapi/src/lib/model/taskAndDestinationNameObject.ts
  libs/perun/openapi/src/lib/model/taskResultIdObject.ts
Labels: requested changes

#446 Resource list - height of rows
  libs/perun/components/src/lib/resources-list/resources-list.component.scss
Labels: requested changes

#454 Vo/Group application form - copy form dialog
  apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.html
Labels: waiting for review

#453 User profile bugfixes
  apps/user-profile/src/app/pages/identities-page/identities-page.component.html
  apps/user-profile/src/app/pages/settings-page/settings-ssh-keys/settings-ssh-keys.component.html
  apps/user-profile/src/app/pages/settings-page/settings-ssh-keys/settings-ssh-keys.component.scss
  apps/user-profile/src/app/services/user-profile-config.service.ts
  apps/user-profile/src/assets/i18n/cz.json
  apps/user-profile/src/assets/i18n/en.json
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.html
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.scss
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.ts
Labels: waiting for review

#445 Small fixes in facility section
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-facility-dialog/create-facility-dialog.component.html
  apps/admin-gui/src/app/shared/components/facility-select-table/facility-select-table.component.html
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#435 Group Authorization
  apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/create-relation-dialog/create-relation-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-relation-dialog/create-relation-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/edit-email-footer-dialog/edit-email-footer-dialog.component.ts
  apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts
  apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.html
  apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.ts
  apps/admin-gui/src/app/vos/components/application-list-details/application-list-details.component.html
  apps/admin-gui/src/app/vos/components/application-list-details/application-list-details.component.scss
  apps/admin-gui/src/app/vos/components/application-list-details/application-list-details.component.ts
  apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.html
  apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.scss
  apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.ts
  apps/admin-gui/src/app/vos/components/members-list/members-list.component.html
  apps/admin-gui/src/app/vos/components/members-list/members-list.component.scss
  apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.html
  apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.scss
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-relations/group-settings-relations.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-relations/group-settings-relations.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/components/src/lib/groups-tree/groups-tree.component.html
  libs/perun/components/src/lib/groups-tree/groups-tree.component.ts
  libs/perun/components/src/lib/resources-list/resources-list.component.html
  libs/perun/components/src/lib/resources-list/resources-list.component.ts
Labels: Very High Priority, waiting for review

#437 Settings-AdvancedSettings, attributes moved to overview
  apps/admin-gui/src/app/admin/admin-routing.module.ts
  apps/admin-gui/src/app/app-routing.module.ts
  apps/admin-gui/src/app/facilities/facilities-routing.module.ts
  apps/admin-gui/src/app/facilities/facilities.module.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-attributes/facility-attributes.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-attributes/facility-attributes.component.scss
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-attributes/facility-attributes.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.scss
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-overview/resource-settings-overview.component.ts
  apps/admin-gui/src/app/shared/components/user-detail-page/user-attributes/user-attributes.component.html
  apps/admin-gui/src/app/shared/components/user-detail-page/user-attributes/user-attributes.component.scss
  apps/admin-gui/src/app/shared/components/user-detail-page/user-attributes/user-attributes.component.ts
  apps/admin-gui/src/app/shared/components/user-detail-page/user-overview/user-overview.component.ts
  apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-overview/user-settings-overview.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-attributes/group-attributes.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-attributes/group-attributes.component.scss
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-attributes/group-attributes.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts
  apps/admin-gui/src/app/vos/vos-routing.module.ts
  apps/admin-gui/src/app/vos/vos.module.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: Very High Priority, waiting for review

#434 Group invitation
  apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for rebase

#447 Undefined error message
  libs/perun/services/src/lib/notificator.service.ts
Labels: waiting for review

#455 Reload principal
  apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts
  apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts
  libs/perun/services/src/lib/init-auth.service.ts
Labels: waiting for review

#456 Remove suspended status
  apps/admin-gui/src/app/shared/pipes/member-status-icon.pipe.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
  libs/perun/services/src/lib/members.service.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for review

#463 Search select
  apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/components/src/lib/vo-search-select/vo-search-select.component.css
  libs/perun/components/src/lib/vo-search-select/vo-search-select.component.html
  libs/perun/components/src/lib/vo-search-select/vo-search-select.component.spec.ts
  libs/perun/components/src/lib/vo-search-select/vo-search-select.component.ts
  package-lock.json
  package.json
Labels: waiting for review

#450 Member list logins
  apps/admin-gui/src/app/vos/components/members-list/members-list.component.html
  apps/admin-gui/src/app/vos/components/members-list/members-list.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for rebase

#441 loading to overviews added
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.ts
  apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.html
  apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-overview/resource-settings-overview.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-overview/resource-settings-overview.component.ts
  apps/admin-gui/src/app/shared/components/user-detail-page/user-dashboard/user-dashboard.component.html
  apps/admin-gui/src/app/shared/components/user-detail-page/user-dashboard/user-dashboard.component.ts
  apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-overview/user-settings-overview.component.html
  apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-overview/user-settings-overview.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-detail-page.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-overview/vo-settings-overview.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-overview/vo-settings-overview.component.ts
Labels: waiting for review

#443 Delete loa
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-user-ext-source-dialog/add-user-ext-source-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-user-ext-source-dialog/add-user-ext-source-dialog.component.ts
  apps/admin-gui/src/app/vos/components/application-list-details/application-list-details.component.html
  apps/admin-gui/src/app/vos/components/application-list-details/application-list-details.component.ts
  apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.html
  apps/admin-gui/src/app/vos/components/expiration-settings/expiration-settings.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-applications/member-applications.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.ts
  apps/user-profile/src/app/pages/identities-page/identities-page.component.ts
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.html
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.ts
Labels: waiting for review

#433 Resource assgined members
  apps/admin-gui/src/app/facilities/facilities-routing.module.ts
  apps/admin-gui/src/app/facilities/facilities.module.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-members/resource-assigned-members.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-members/resource-assigned-members.component.scss
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-members/resource-assigned-members.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html
  apps/admin-gui/src/app/vos/vos-routing.module.ts
  apps/admin-gui/src/app/vos/vos.module.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/config/table-config/src/lib/table-config.service.ts
  libs/perun/components/src/lib/change-expiration-dialog/change-expiration-dialog.component.spec.ts
  libs/perun/components/src/lib/change-member-status-dialog/change-member-status-dialog.component.html
  libs/perun/components/src/lib/change-member-status-dialog/change-member-status-dialog.component.scss
  libs/perun/components/src/lib/change-member-status-dialog/change-member-status-dialog.component.ts
  libs/perun/components/src/lib/members-list/members-list.component.html
  libs/perun/components/src/lib/members-list/members-list.component.scss
  libs/perun/components/src/lib/members-list/members-list.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/components/src/lib/remove-user-ext-source-dialog/remove-user-ext-source-dialog.component.spec.ts
  libs/perun/openapi/src/lib/model/member.ts
  libs/perun/pipes/src/index.ts
  libs/perun/pipes/src/lib/member-email.pipe.ts
  libs/perun/pipes/src/lib/member-status-icon-color.pipe.ts
  libs/perun/pipes/src/lib/member-status-icon.pipe.ts
  libs/perun/pipes/src/lib/member-status-tooltip.pipe.ts
  libs/perun/pipes/src/lib/perun-pipes.module.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for rebase

#478 Edit group dialog update
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.scss
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/index.ts
  libs/perun/components/src/lib/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.html
  libs/perun/components/src/lib/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.scss
  libs/perun/components/src/lib/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.spec.ts
  libs/perun/components/src/lib/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.ts
  libs/perun/components/src/lib/edit-group-dialog/edit-group-dialog.component.html
  libs/perun/components/src/lib/edit-group-dialog/edit-group-dialog.component.spec.ts
  libs/perun/components/src/lib/edit-group-dialog/edit-group-dialog.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/components/src/lib/groups-tree/groups-tree.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  package-lock.json
Labels: waiting for review

#475 Group synch indication
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/index.ts
Labels: waiting for rebase

#490 Member list logins
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-members/resource-assigned-members.component.html
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
  libs/perun/components/src/lib/members-list/members-list.component.html
  libs/perun/components/src/lib/members-list/members-list.component.ts
  libs/perun/pipes/src/index.ts
  libs/perun/pipes/src/lib/member-logins.pipe.ts
  libs/perun/pipes/src/lib/perun-pipes.module.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for review
