Repository CESNET/perun-web-apps, pull requests merged in 2021-09, with the labels that each got.

#797 feat(admin): add support for Basic Auth
  apps/admin-gui/src/app/app-routing.module.ts
  apps/admin-gui/src/app/app.component.html
  apps/admin-gui/src/app/app.component.ts
  apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/login/src/index.ts
  libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.css
  libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.html
  libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.ts
  libs/perun/login/src/lib/perun-login.module.ts
  libs/perun/services/src/lib/ApiInterceptor.ts
  libs/perun/services/src/lib/auth.service.ts
  libs/perun/services/src/lib/init-auth.service.ts
Labels: waiting for review

#837 ci(githubci): add alpha and beta releases
  .releaserc.json
Labels: waiting for review

#840 style: unify logo position in all applications
  apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.html
  apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.scss
  apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.ts
  apps/admin-gui/src/assets/config/defaultConfig.json
  apps/publications/src/app/components/header/header.component.html
  apps/publications/src/app/components/header/header.component.scss
  apps/user-profile/src/app/app.component.html
  apps/user-profile/src/app/app.component.ts
  apps/user-profile/src/app/components/header/header.component.html
  apps/user-profile/src/app/components/header/header.component.scss
  apps/user-profile/src/styles.scss
  libs/perun/login/src/lib/login-screen-base/login-screen-base.component.html
  libs/perun/login/src/lib/login-screen-base/login-screen-base.component.scss
  libs/perun/login/src/lib/login-screen-base/login-screen-base.component.ts
  libs/perun/login/src/lib/login-screen/login-screen.component.html
Labels: waiting for review

#838 fix(admin): show all members on resource-member attributes page
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.ts
  apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts
  libs/perun/openapi/src/lib/model/assignedMember.ts
Labels: waiting for rebase

#842 fix: align footer items
  libs/perun/components/src/lib/perun-footer/perun-footer.component.html
  libs/perun/components/src/lib/perun-footer/perun-footer.component.scss
Labels: waiting for review

#844 fix: use better email regex
  apps/admin-gui/src/app/shared/components/add-owner-dialog/add-owner-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-services-destination-dialog/add-services-destination-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts
  libs/perun/utils/src/lib/perun-utils.ts
  package-lock.json
Labels: waiting for review

#845 feat(admin-gui): enable basic auth
  libs/perun/services/src/lib/auth.service.ts
Labels: waiting for review

#841 feat(user-profile): change password
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
  libs/perun/components/src/lib/password-reset/password-reset.component.html
  libs/perun/components/src/lib/password-reset/password-reset.component.ts
  libs/perun/dialogs/src/lib/change-password-dialog/change-password-dialog.component.css
  libs/perun/dialogs/src/lib/change-password-dialog/change-password-dialog.component.html
  libs/perun/dialogs/src/lib/change-password-dialog/change-password-dialog.component.ts
  libs/perun/dialogs/src/lib/perun-dialogs.module.ts
Labels: waiting for review

#849 fix(publications): fix bug on create single publication page
  apps/publications/src/app/pages/create-publication-page/create-single-publication-page/create-single-publication-page.component.html
  apps/publications/src/app/pages/create-publication-page/create-single-publication-page/create-single-publication-page.component.ts
Labels: waiting for review

#846 feat(admin): add all assignment statuses to group/resource attribute settings
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.ts
  apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html
  apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.ts
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.css
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
  libs/perun/components/src/lib/group-search-select/group-search-select.component.html
  libs/perun/components/src/lib/group-search-select/group-search-select.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/components/src/lib/resource-search-select/resource-search-select.component.html
  libs/perun/components/src/lib/resources-list/resources-list.component.ts
  libs/perun/models/src/index.ts
  libs/perun/models/src/lib/GroupWithStatus.ts
  libs/perun/models/src/lib/ResourceWithStatus.ts
Labels: waiting for review

#850 feat: filter attributes by Urns
  libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
  package-lock.json
Labels: waiting for review

#852 fix(admin-gui): fix of policies when getting attributes
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-attributes/group-attributes.component.ts
Labels: waiting for review

#854 feat(admin): fixed notification when creating service member
  apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#853 fix: add mat ripple to publications and user profile
  apps/publications/src/app/components/side-menu/side-menu.component.html
  apps/publications/src/app/services/side-menu-items.service.ts
  apps/user-profile/src/app/components/side-menu/side-menu.component.html
  libs/ui/material/src/lib/ui-material.module.ts
Labels: waiting for review

#851 feat(admin-gui): show automatically assigned subgroups/resources
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-relation-dialog/create-relation-dialog.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/components/src/lib/resources-list/resources-list.component.html
  libs/perun/components/src/lib/resources-list/resources-list.component.ts
  libs/perun/models/src/lib/GroupWithStatus.ts
  libs/perun/models/src/lib/ResourceWithStatus.ts
Labels: waiting for review

#848 style: unify info/warn/error alerts
  apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.html
  apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/connect-identity-dialog/connect-identity-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-definition-dialog/delete-attribute-definition-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/remove-destination-dialog/remove-destination-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/entityless-attribute-keys-list/entityless-attribute-keys-list.component.html
  apps/admin-gui/src/app/shared/components/member-overview-groups/member-overview-groups.component.html
  apps/admin-gui/src/app/vos/components/application-form-manage-groups/application-form-manage-groups.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-states/vo-resources-states.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.html
  apps/publications/src/app/components/authors-list/authors-list.component.html
  apps/publications/src/app/components/publication-systems-list/publication-systems-list.component.html
  apps/publications/src/app/components/thanks-list/thanks-list.component.html
  apps/publications/src/app/dialogs/add-authors-dialog/add-authors-dialog.component.html
  apps/publications/src/app/pages/create-publication-page/import-publications-page/import-publications-page.component.html
  apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.html
  libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html
  libs/perun/components/src/lib/members-list/members-list.component.html
  libs/ui/alerts/src/lib/alert/alert.component.css
  libs/ui/alerts/src/lib/alert/alert.component.html
Labels: waiting for review

#855 feat(admin): improve assigning service packages to resource
  apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
  libs/perun/components/src/lib/service-package-search-select/service-package-search-select.component.html
  libs/perun/components/src/lib/service-package-search-select/service-package-search-select.component.ts
Labels: requested changes

#856 fix(admin): fix infinite loading at dashboard buttons
  apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
Labels: waiting for review

#847 feat(admin): assign group to resource with modifiers
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/config/table-config/src/lib/table-config.service.ts
  libs/perun/openapi/src/lib/api/resourcesManager.service.ts
  libs/perun/openapi/src/lib/model/assignedGroup.ts
  libs/perun/openapi/src/lib/model/assignedMember.ts
  libs/perun/openapi/src/lib/model/assignedResource.ts
Labels: waiting for review

#859 feat(admin): fix enity description restrictions
  apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.ts
  libs/perun/dialogs/src/lib/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.html
  libs/perun/dialogs/src/lib/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.ts
Labels: waiting for review

#861 fix(admin): adding new ues attributes
  apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.ts
Labels: waiting for review

#862 feat(admin): allow setting member expiration in future
  apps/admin-gui/src/app/shared/components/member-overview-membership/member-overview-membership.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.css
  libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.html
  libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.ts
  libs/perun/dialogs/src/lib/change-group-expiration-dialog/change-group-expiration-dialog.component.html
  libs/perun/dialogs/src/lib/change-group-expiration-dialog/change-group-expiration-dialog.component.ts
  libs/perun/dialogs/src/lib/change-vo-expiration-dialog/change-vo-expiration-dialog.component.html
  libs/perun/dialogs/src/lib/change-vo-expiration-dialog/change-vo-expiration-dialog.component.ts
Labels: waiting for review

#865 fix: run the lint on all projects
  libs/perun/components/src/lib/password-reset/password-reset.component.ts
  libs/perun/components/src/lib/vos-list/vos-list.component.ts
  libs/perun/dialogs/src/index.ts
  libs/perun/dialogs/src/lib/perun-dialogs.module.ts
  libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.ts
  libs/perun/services/src/lib/api.service.ts
  libs/perun/services/src/lib/perun-api-service.ts
  package.json
Labels: waiting for review

#864 fix(lib): disable deleting persistent ues
  apps/admin-gui/src/assets/i18n/en.json
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.html
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.ts
Labels: waiting for review

#866 feat(admin): change label of submit button in Change group resource assignment dialog
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.html
Labels: waiting for review
