Repository CESNET/perun-web-apps, pull requests merged in 2021-06, with the labels that each got.

#723 fix textarea
  apps/admin-gui/src/styles.scss
Labels: waiting for review

#724 Session expiration dialog behaviour
  libs/perun/services/src/lib/ApiInterceptor.ts
  libs/perun/services/src/lib/auth.service.ts
  libs/perun/session-expiration/src/lib/session-expiration-dialog/session-expiration-dialog.component.html
  libs/perun/session-expiration/src/lib/session-expiration-dialog/session-expiration-dialog.component.ts
Labels: waiting for review

#722 Invalid preferred mail change request handling
  apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  apps/user-profile/src/app/pages/profile-page/profile-page.component.ts
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
  libs/perun/dialogs/src/index.ts
  libs/perun/dialogs/src/lib/mail-change-failed-dialog/mail-change-failed-dialog.component.html
  libs/perun/dialogs/src/lib/mail-change-failed-dialog/mail-change-failed-dialog.component.scss
  libs/perun/dialogs/src/lib/mail-change-failed-dialog/mail-change-failed-dialog.component.ts
  libs/perun/dialogs/src/lib/perun-dialogs.module.ts
Labels: waiting for review

#725 edit of sponsorship added into the member overview
  apps/admin-gui/src/app/shared/components/dialogs/edit-member-sponsors-dialog/edit-member-sponsors-dialog.component.ts
  apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/pipes/src/lib/parse-date.pipe.ts
Labels: waiting for review

#726 change of initial value of select status in page vo-members to no sta…
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#730 Package.json version increased
  package.json
Labels: waiting for review

#732 cleanup of unused components and paths to those components
  apps/admin-gui/src/app/admin/admin-routing.module.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-facility-attributes/user-settings-facility-attributes.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-facility-attributes/user-settings-facility-attributes.component.scss
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-facility-attributes/user-settings-facility-attributes.component.ts
  apps/admin-gui/src/app/users/users-routing.module.ts
  apps/admin-gui/src/app/users/users.module.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-resource-attributes/group-settings-resource-attributes.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-resource-attributes/group-settings-resource-attributes.component.scss
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-resource-attributes/group-settings-resource-attributes.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-group-attributes/member-settings-group-attributes.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-group-attributes/member-settings-group-attributes.component.scss
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-group-attributes/member-settings-group-attributes.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.scss
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-resource-attributes/member-settings-resource-attributes.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-resource-attributes/member-settings-resource-attributes.component.scss
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-resource-attributes/member-settings-resource-attributes.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings.component.scss
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings.component.ts
  apps/admin-gui/src/app/vos/vos-routing.module.ts
  apps/admin-gui/src/app/vos/vos.module.ts
Labels: waiting for review

#731 add user and facility-user attributes as tab to member attributes page
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-attributes/facility-attributes.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-attributes/facility-attributes.component.ts
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.ts
  apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.css
  apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.html
  apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.ts
  apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-attributes/user-attributes.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-attributes/user-attributes.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-attributes/group-attributes.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-attributes/group-attributes.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-attributes/vo-attributes.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-attributes/vo-attributes.component.ts
Labels: waiting for review

#735 changes in member-overview.component - creating new component for mem…
  apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.scss
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview-membership/member-overview-membership.component.css
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview-membership/member-overview-membership.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview-membership/member-overview-membership.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts
  apps/admin-gui/src/app/vos/vos.module.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for review

#728 Added import for publications from external systems
  apps/publications/src/app/app-routing.module.ts
  apps/publications/src/app/app.module.ts
  apps/publications/src/app/components/publication-filter/publication-filter.component.html
  apps/publications/src/app/components/publication-filter/publication-filter.component.ts
  apps/publications/src/app/components/publications-list/publications-list.component.html
  apps/publications/src/app/components/publications-list/publications-list.component.ts
  apps/publications/src/app/components/year-range/year-range.component.html
  apps/publications/src/app/components/year-range/year-range.component.scss
  apps/publications/src/app/components/year-range/year-range.component.ts
  apps/publications/src/app/pages/create-publication-page/create-publication-page.component.html
  apps/publications/src/app/pages/create-publication-page/create-publication-page.component.ts
  apps/publications/src/app/pages/create-publication-page/import-publications-page/import-publications-page.component.html
  apps/publications/src/app/pages/create-publication-page/import-publications-page/import-publications-page.component.scss
  apps/publications/src/app/pages/create-publication-page/import-publications-page/import-publications-page.component.ts
  apps/publications/src/app/pages/publication-detail/publication-detail.component.ts
  apps/publications/src/assets/i18n/en.json
  libs/config/table-config/src/lib/table-config.service.ts
  libs/perun/dialogs/src/lib/perun-dialogs.module.ts
  libs/perun/dialogs/src/lib/universal-confirmation-dialog/universal-confirmation-dialog.component.html
  libs/perun/dialogs/src/lib/universal-confirmation-dialog/universal-confirmation-dialog.component.scss
  libs/perun/dialogs/src/lib/universal-confirmation-dialog/universal-confirmation-dialog.component.ts
Labels: dont merge, waiting for review

#736 fix filtering in sponsored members and members list
  apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.ts
  libs/perun/components/src/lib/members-list/members-list.component.ts
Labels: waiting for review

#737 remove unused and useless core from generate-sponsored-members
  apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts
Labels: waiting for review

#734 Fixed texts for instances withotu cs localisation
  apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.ts
  apps/admin-gui/src/app/vos/components/application-form-preview/application-form-preview.component.html
  apps/admin-gui/src/app/vos/components/application-form-preview/application-form-preview.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.ts
  apps/admin-gui/src/assets/config/defaultConfig.json
  apps/publications/src/assets/config/defaultConfig.json
  apps/user-profile/src/assets/config/defaultConfig.json
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for review

#739 fix(admin-gui): Show disabled config for username app item
  apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.ts
Labels: waiting for review

#741 Added option for change member status
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview-membership/member-overview-membership.component.css
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview-membership/member-overview-membership.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview-membership/member-overview-membership.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.html
  libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.scss
  libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.ts
  libs/perun/dialogs/src/lib/change-member-status-dialog/change-member-status-dialog.component.html
  libs/perun/dialogs/src/lib/change-member-status-dialog/change-member-status-dialog.component.scss
  libs/perun/dialogs/src/lib/change-member-status-dialog/change-member-status-dialog.component.ts
  libs/perun/dialogs/src/lib/perun-dialogs.module.ts
  libs/perun/openapi/src/lib/api/groupsManager.service.ts
  libs/perun/openapi/src/lib/api/membersManager.service.ts
  libs/perun/openapi/src/lib/api/resourcesManager.service.ts
  libs/perun/pipes/src/lib/parse-date.pipe.ts
Labels: requested changes, waiting for review

#743 Fix supported languages
  apps/admin-gui/src/assets/config/defaultConfig.json
  apps/user-profile/src/assets/config/defaultConfig.json
Labels: waiting for review

#744 feat(admin-gui): Show urn on attr display names
  libs/perun/components/src/lib/attributes-list/attributes-list.component.html
  libs/perun/components/src/lib/attributes-list/attributes-list.component.scss
  libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
Labels: waiting for review

#746 Added UUID to entity detail
  apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/components/src/lib/groups-tree/groups-tree.component.ts
  libs/perun/components/src/lib/resources-list/resources-list.component.ts
  libs/perun/openapi/src/lib/api/facilitiesManager.service.ts
  libs/perun/openapi/src/lib/api/groupsManager.service.ts
  libs/perun/openapi/src/lib/api/resourcesManager.service.ts
  libs/perun/openapi/src/lib/model/group.ts
  libs/perun/openapi/src/lib/model/models.ts
  libs/perun/openapi/src/lib/model/resource.ts
  libs/perun/openapi/src/lib/model/user.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for review

#745 Allowed displaying short names instead of labels on preview
  apps/admin-gui/src/app/vos/components/application-form-preview/application-form-preview.component.ts
Labels: waiting for review
