Repository CESNET/perun-web-apps, pull requests merged in 2021-11, with the labels that each got.

#895 fix: password-reset app uses new oidc library
  apps/password-reset/src/app/app.module.ts
Labels: waiting for review

#899 feat(profile): address change password through URL
  libs/perun/components/src/lib/password-reset/password-reset.component.ts
Labels: waiting for review

#901 feat(admin): show whole error message when setting up a password
  libs/perun/namespace-password-form/src/lib/password-form/password-form.component.html
  libs/perun/namespace-password-form/src/lib/password-form/password-form.component.scss
Labels: waiting for review

#896 feat: Set lang and auth filter in password-reset
  apps/password-reset/src/app/app.component.ts
  apps/password-reset/src/app/services/password-reset-config.service.ts
  apps/password-reset/src/assets/config/defaultConfig.json
Labels: waiting for review

#904 fix(admin): fix of user account page
  apps/admin-gui/src/app/users/pages/user-detail-page/user-accounts/user-accounts.component.html
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#902 feat(admin): warn before disconnecting users from service accounts
  apps/admin-gui/src/app/shared/components/dialogs/disconnect-identity-dialog/disconnect-identity-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/disconnect-identity-dialog/disconnect-identity-dialog.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#903 feat: address link to new pwd reset app in email message
  apps/admin-gui/src/app/shared/components/dialogs/password-reset-request-dialog/password-reset-request-dialog.component.ts
  libs/perun/openapi/src/lib/api/membersManager.service.ts
Labels: waiting for review

#912 fix(lib): show alert icon at top
  libs/ui/alerts/src/lib/alert/alert.component.html
Labels: waiting for review

#913 fix(admin): use placeholders in application settings dialog
  apps/admin-gui/src/app/shared/components/dialogs/update-application-form-dialog/update-application-form-dialog.component.html
Labels: waiting for review

#915 feat(admin): shorten object names at dashboard
  apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.scss
Labels: waiting for review

#914 feat(admin): unify elements of attributes settings
  apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html
  apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
Labels: waiting for review

#908 feat: Ellipsis in action button text
  apps/admin-gui/src/app/admin/pages/admin-page/admin-attributes/admin-attributes.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-owners/admin-owners.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/admin-services.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-required-attributes/service-required-attributes.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-owners/facility-settings-owners.component.html
  apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-tags/resource-tags.component.html
  apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html
  apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.html
  apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-identities/user-identities.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-associated-users/user-settings-associated-users.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/user-settings-service-identities.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-extsources/group-settings-extsources.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-relations/group-settings-relations.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-resources/member-resources.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-tags/vo-resources-tags.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-extsources/vo-settings-extsources.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-service-members/vo-settings-service-members.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.html
  apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.html
  apps/admin-gui/src/styles.scss
  apps/publications/src/app/components/add-authors/add-authors.component.html
  apps/publications/src/app/components/add-thanks/add-thanks.component.html
  apps/publications/src/app/pages/categories-page/categories-page.component.html
  apps/publications/src/app/pages/create-publication-page/create-publication-page.component.html
  apps/publications/src/styles.scss
  apps/user-profile/src/app/pages/identities-page/identities-page.component.html
  apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.html
  apps/user-profile/src/app/pages/settings-page/settings-preferred-unix-group-names/settings-preferred-unix-group-names.component.html
  apps/user-profile/src/app/pages/settings-page/settings-ssh-keys/settings-ssh-keys.component.html
  apps/user-profile/src/styles.scss
  libs/perun/components/src/lib/password-reset/password-reset.component.html
Labels: waiting for review

#911 fix(admin-gui): english spelling
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#910 fix: center checkboxes in tables
  apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html
  apps/admin-gui/src/app/shared/components/blacklist-list/blacklist-list.component.html
  apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.html
  apps/admin-gui/src/app/shared/components/entityless-attribute-keys-list/entityless-attribute-keys-list.component.html
  apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.html
  apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html
  apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.html
  apps/admin-gui/src/app/shared/components/resources-tags-list/resources-tags-list.component.html
  apps/admin-gui/src/app/shared/components/security-teams-list/security-teams-list.component.html
  apps/admin-gui/src/app/shared/components/services-list/services-list.component.html
  apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html
  apps/admin-gui/src/app/shared/components/users-list/users-list.component.html
  apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.html
  apps/admin-gui/src/styles.scss
  apps/publications/src/app/components/authors-list/authors-list.component.html
  apps/publications/src/app/components/categories-list/categories-list.component.html
  apps/publications/src/app/components/publications-list/publications-list.component.html
  apps/publications/src/app/components/thanks-list/thanks-list.component.html
  apps/user-profile/src/app/components/membership-list/membership-list.component.html
  apps/user-profile/src/app/components/string-list/string-list.component.html
  libs/perun/components/src/lib/attributes-list/attributes-list.component.html
  libs/perun/components/src/lib/facilities-list/facilities-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html
  libs/perun/components/src/lib/members-list/members-list.component.html
  libs/perun/components/src/lib/owners-list/owners-list.component.html
  libs/perun/components/src/lib/resources-list/resources-list.component.html
  libs/perun/components/src/lib/services-status-list/services-status-list.component.html
  libs/perun/components/src/lib/task-results-list/task-results-list.component.html
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.html
  libs/perun/components/src/lib/users-dynamic-list/users-dynamic-list.component.html
  libs/perun/components/src/lib/vos-list/vos-list.component.html
Labels: waiting for rebase

#906 fix: urls to other applications based on brand configuration
  apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts
  apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.ts
  apps/admin-gui/src/assets/config/defaultConfig.json
  apps/user-profile/src/app/components/header/header.component.ts
  apps/user-profile/src/app/services/user-profile-config.service.ts
  apps/user-profile/src/assets/config/defaultConfig.json
  libs/config/src/lib/app-config.service.ts
  libs/perun/components/src/lib/password-reset/password-reset.component.ts
  libs/perun/services/src/index.ts
  libs/perun/services/src/lib/force-router.service.ts
  libs/perun/services/src/lib/other-applications.service.ts
  libs/perun/services/src/lib/store.service.ts
Labels: waiting for review

#918 feat(admin): unify spaces between buttons
  apps/admin-gui/src/app/admin/pages/admin-page/admin-owners/admin-owners.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/admin-services.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-required-attributes/service-required-attributes.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html
  apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-tags/resource-tags.component.html
  apps/admin-gui/src/app/shared/components/dialogs/attribute-import-dialog/attribute-import-dialog.component.html
  apps/admin-gui/src/app/shared/components/identity-detail/identity-detail.component.html
  apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.html
  apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-extsources/group-settings-extsources.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-relations/group-settings-relations.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-applications/member-applications.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-resources/member-resources.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-preview/vo-resources-preview.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-tags/vo-resources-tags.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-extsources/vo-settings-extsources.component.html
  apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.html
  apps/publications/src/app/components/add-authors/add-authors.component.html
  apps/publications/src/app/components/add-thanks/add-thanks.component.html
  apps/publications/src/app/components/authors-list/authors-list.component.html
  apps/publications/src/app/components/authors-list/authors-list.component.scss
  apps/publications/src/app/components/publications-list/publications-list.component.html
  apps/publications/src/app/components/publications-list/publications-list.component.scss
  apps/publications/src/app/pages/categories-page/categories-page.component.html
  libs/perun/components/src/lib/date-range/date-range.component.html
  libs/perun/components/src/lib/debounce-filter/debounce-filter.component.html
  libs/perun/components/src/lib/immediate-filter/immediate-filter.component.html
Labels: waiting for review

#925 fix(admin): reserve password for service account with correct rights
  apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.ts
Labels: waiting for review

#921 fix(admin): lable of Attribute definitions in perun admin section
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#922 fix(admin): Identity page unification
  apps/admin-gui/src/app/users/pages/user-detail-page/user-identities/user-identities.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-identities/user-identities.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.html
  libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.ts
Labels: waiting for review

#923 fix(admin): "Id" unification
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#926 fix(admin): missing text in create sponsored member dialog
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#927 feat(admin): use estimated count of audit messages in custom paginator
  apps/admin-gui/src/app/shared/components/audit-messages-list/audit-messages-list.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/services/src/index.ts
  libs/perun/services/src/lib/custom-mat-paginator.ts
Labels: waiting for review

#928 feat(admin): improve audit message detail component
  apps/admin-gui/src/app/shared/components/audit-messages-list/audit-messages-list.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/audit-message-detail-dialog/audit-message-detail-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/audit-message-detail-dialog/audit-message-detail-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/audit-message-detail-dialog/audit-message-detail-dialog.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#916 feat(admin): service identity terminology unification
  apps/admin-gui/src/app/shared/components/dialogs/connect-identity-dialog/connect-identity-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/connect-identity-dialog/connect-identity-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/disconnect-identity-dialog/disconnect-identity-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/disconnect-identity-dialog/disconnect-identity-dialog.component.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-associated-users/user-settings-associated-users.component.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/user-settings-service-identities.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#934 fix(admin): fix loading of resource attributes
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.ts
Labels: waiting for review

#939 fix(admin): fix loading of changing status of group-resource status
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.html
Labels: waiting for review

#930 feat(admin): improve UX of dialogs that use stepper
  apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts
Labels: waiting for review

#920 fix(admin): fix assign group/assign resource button auth
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.ts
Labels: waiting for review, waiting for rebase
