Repository CESNET/perun-web-apps, pull requests merged in 2022-09, with the labels that each got.

#1124 feat(admin): e2e tests for TRUSTEDFACILITYADMIN
  apps/admin-gui-e2e/cypress.config.ts
  apps/admin-gui-e2e/src/e2e/trusted-facility-admin-perun_admin.cy.js
  apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html
  libs/perun/components/src/lib/group-resource-status/group-resource-status.component.html
  libs/perun/components/src/lib/group-resource-status/group-resource-status.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.html
Labels: requested changes

#1134 feat(admin): e2e tests for GROUPOBSERVER
  apps/admin-gui-e2e/cypress.config.ts
  apps/admin-gui-e2e/src/e2e/group-management-group_observer.cy.js
  apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.html
  apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.html
  apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.html
  libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html
Labels: waiting for review

#1139 feat(admin): e2e tests for FACILITYOBSERVER
  apps/admin-gui-e2e/cypress.config.ts
  apps/admin-gui-e2e/src/e2e/facility-management-facility_observer.cy.js
  apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.html
  apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html
  libs/perun/components/src/lib/attributes-list/attributes-list.component.html
  libs/perun/components/src/lib/owners-list/owners-list.component.html
  libs/perun/components/src/lib/services-status-list/services-status-list.component.html
  libs/perun/components/src/lib/task-results-list/task-results-list.component.html
  libs/perun/pipes/src/lib/multi-word-data-cy.pipe.ts
Labels: waiting for review

#1138 fix(admin): do not change tab when removed manager
  apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts
Labels: waiting for review

#1133 feat(admin): e2e tests for RESOURCEOBSERVER
  apps/admin-gui-e2e/cypress.config.ts
  apps/admin-gui-e2e/src/e2e/resource-observer-perun_admin.cy.js
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html
Labels: waiting for rebase

#1137 feat(admin): e2e tests for VOOBSERVER
  apps/admin-gui-e2e/cypress.config.ts
  apps/admin-gui-e2e/src/e2e/vo-observer-perun_admin.cy.js
  apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-detail-page.component.html
Labels: waiting for rebase

#1135 fix(admin): set service to entity storage service
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.ts
Labels: waiting for review

#1136 fix(admin): add missing refresh button
  apps/admin-gui/src/app/admin/pages/admin-page/admin-ext-sources/admin-ext-sources.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#1140 feat(admin): scroll to top of table on page change
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.html
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
Labels: waiting for review

#1141 feat(admin): add groupmembershipmanager role
  apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-roles/group-roles.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/models/src/lib/PerunPrincipal.ts
Labels: waiting for review

#1142 feat(admin): e2e tests for PERUNOBSERVER
  apps/admin-gui-e2e/cypress.config.ts
  apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_observer.cy.js
  apps/admin-gui/src/app/admin/pages/admin-page/admin-attributes/admin-attributes.component.html
  apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html
  apps/admin-gui/src/app/shared/components/audit-messages-list/audit-messages-list.component.html
  apps/admin-gui/src/app/shared/components/dialogs/audit-message-detail-dialog/audit-message-detail-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-definition-dialog/edit-attribute-definition-dialog.component.html
Labels: waiting for review

#1132 feat(admin): e2e tests for SPONSOR
  apps/admin-gui-e2e/cypress.config.ts
  apps/admin-gui-e2e/src/e2e/sponsor-management-perun_admin.cy.js
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-member-sponsors-dialog/edit-member-sponsors-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/password-reset-request-dialog/password-reset-request-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.html
  libs/perun/components/src/lib/members-list/members-list.component.html
  libs/perun/namespace-password-form/src/lib/password-form/password-form.component.html
Labels: waiting for rebase

#1128 feat(admin): update of the Table-Checkbox service
  apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html
  apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.ts
  apps/admin-gui/src/app/shared/components/blacklist-list/blacklist-list.component.html
  apps/admin-gui/src/app/shared/components/blacklist-list/blacklist-list.component.ts
  apps/admin-gui/src/app/shared/components/consent-hubs-list/consent-hubs-list.component.html
  apps/admin-gui/src/app/shared/components/consent-hubs-list/consent-hubs-list.component.ts
  apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.html
  apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.ts
  apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.html
  apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.ts
  apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html
  apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.ts
  apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.html
  apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.ts
  apps/admin-gui/src/app/shared/components/resources-tags-list/resources-tags-list.component.html
  apps/admin-gui/src/app/shared/components/resources-tags-list/resources-tags-list.component.ts
  apps/admin-gui/src/app/shared/components/security-teams-list/security-teams-list.component.html
  apps/admin-gui/src/app/shared/components/security-teams-list/security-teams-list.component.ts
  apps/admin-gui/src/app/shared/components/services-list/services-list.component.html
  apps/admin-gui/src/app/shared/components/services-list/services-list.component.ts
  apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html
  apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.ts
  apps/admin-gui/src/app/shared/components/users-list/users-list.component.html
  apps/admin-gui/src/app/shared/components/users-list/users-list.component.ts
  apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.html
  apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.ts
  apps/publications/src/app/components/categories-list/categories-list.component.ts
  apps/publications/src/app/components/publications-list/publications-list.component.html
  apps/publications/src/app/components/publications-list/publications-list.component.ts
  apps/publications/src/app/components/thanks-list/thanks-list.component.html
  apps/publications/src/app/components/thanks-list/thanks-list.component.ts
  libs/perun/components/src/lib/attributes-list/attributes-list.component.html
  libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
  libs/perun/components/src/lib/consents-list/consents-list.component.html
  libs/perun/components/src/lib/consents-list/consents-list.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/components/src/lib/members-list/members-list.component.html
  libs/perun/components/src/lib/members-list/members-list.component.ts
  libs/perun/components/src/lib/owners-list/owners-list.component.html
  libs/perun/components/src/lib/owners-list/owners-list.component.ts
  libs/perun/components/src/lib/resources-list/resources-list.component.html
  libs/perun/components/src/lib/resources-list/resources-list.component.ts
  libs/perun/components/src/lib/services-status-list/services-status-list.component.html
  libs/perun/components/src/lib/services-status-list/services-status-list.component.ts
  libs/perun/components/src/lib/task-results-list/task-results-list.component.html
  libs/perun/components/src/lib/task-results-list/task-results-list.component.ts
  libs/perun/pipes/src/lib/is-all-selected.pipe.ts
  libs/perun/pipes/src/lib/perun-pipes.module.ts
  libs/perun/services/src/lib/table-checkbox.service.ts
Labels: waiting for review

#1146 fix(admin): add member dialog behavior on MFA error
  apps/admin-gui/src/app/vos/components/add-member.service.ts
  apps/admin-gui/src/app/vos/components/group-add-member-dialog/group-add-member-dialog.component.ts
  apps/admin-gui/src/app/vos/components/vo-add-member-dialog/vo-add-member-dialog.component.ts
Labels: waiting for review
