Repository CESNET/perun-web-apps, pull requests merged in 2022-10, with the labels that each got.

#1148 fix: broken isAllSelected check
  apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html
  apps/admin-gui/src/app/shared/components/blacklist-list/blacklist-list.component.html
  apps/admin-gui/src/app/shared/components/consent-hubs-list/consent-hubs-list.component.html
  apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.html
  apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.html
  apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html
  apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.html
  apps/admin-gui/src/app/shared/components/resources-tags-list/resources-tags-list.component.html
  apps/admin-gui/src/app/shared/components/security-teams-list/security-teams-list.component.html
  apps/admin-gui/src/app/shared/components/services-list/services-list.component.html
  apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html
  apps/admin-gui/src/app/shared/components/users-list/users-list.component.html
  apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.html
  apps/publications/src/app/components/publications-list/publications-list.component.html
  apps/publications/src/app/components/thanks-list/thanks-list.component.html
  libs/perun/components/src/lib/attributes-list/attributes-list.component.html
  libs/perun/components/src/lib/consents-list/consents-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/members-list/members-list.component.html
  libs/perun/components/src/lib/owners-list/owners-list.component.html
  libs/perun/components/src/lib/resources-list/resources-list.component.html
  libs/perun/components/src/lib/services-status-list/services-status-list.component.html
  libs/perun/components/src/lib/task-results-list/task-results-list.component.html
Labels: waiting for review

#1151 feat(admin): fix non-existing form
  apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.ts
Labels: requested changes

#1156 fix: correctly handle RPC error in all components
  apps/admin-gui/src/app/shared/components/member-overview-membership/member-overview-membership.component.ts
  apps/admin-gui/src/app/shared/route-auth-guard.service.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/app/vos/components/add-member.service.ts
  apps/admin-gui/src/app/vos/components/group-add-member-dialog/group-add-member-dialog.component.ts
  apps/admin-gui/src/app/vos/components/vo-add-member-dialog/vo-add-member-dialog.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-expiration/group-settings-expiration.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-expiration/vo-settings-expiration.component.ts
  apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts
  apps/linker/src/app/service/link-identities.service.ts
  apps/user-profile/src/app/pages/consents-page/consent-request/consent-request.component.ts
  libs/perun/namespace-password-form/src/lib/perun-namespace-password-form.ts
  libs/perun/services/src/lib/api.service.ts
Labels: waiting for review

#1095 feat: server side pagination
  apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-relation-dialog/create-relation-dialog.component.html
  apps/admin-gui/src/app/vos/components/application-form-manage-groups/application-form-manage-groups.component.html
  apps/admin-gui/src/app/vos/components/application-form-manage-groups/application-form-manage-groups.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-relations/group-settings-relations.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-relations/group-settings-relations.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts
  apps/admin-gui/src/styles.scss
  apps/publications/src/app/components/authors-list/authors-list.component.ts
  libs/perun/components/src/lib/attribute-unique-toggle/attribute-unique-toggle.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/directives/src/index.ts
  libs/perun/directives/src/lib/loader.directive.ts
  libs/perun/models/src/index.ts
  libs/perun/models/src/lib/DynamicDataSource.ts
  libs/perun/pipes/src/index.ts
  libs/perun/pipes/src/lib/can-manage-group.pipe.ts
  libs/perun/pipes/src/lib/disable-group-select.pipe.ts
  libs/perun/pipes/src/lib/find-attribute.pipe.ts
  libs/perun/pipes/src/lib/group-checkbox-tooltip.pipe.ts
  libs/perun/pipes/src/lib/perun-pipes.module.ts
  libs/perun/services/src/index.ts
  libs/perun/services/src/lib/group-utils.service.ts
  libs/perun/services/src/lib/gui-auth-resolver.service.ts
  libs/perun/services/src/lib/table-checkbox.service.ts
  libs/perun/utils/src/lib/perun-utils.ts
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
Labels: waiting for review

#1149 feat(admin): Service user's managers details
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-associated-users/user-settings-associated-users.component.ts
Labels: waiting for review

#1161 fix: resize window on sidenav reopening
  apps/admin-gui/src/app/app.component.html
  apps/publications/src/app/app.component.html
  apps/user-profile/src/app/app.component.html
Labels: waiting for review

#1158 fix(admin): Hide application form for group members
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts
Labels: waiting for review

#1162 fix(profile): fixed a bug, where if a category in the MFA component d…
  apps/user-profile/src/app/app.module.ts
  apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.html
  apps/user-profile/src/app/pipes/category-label.pipe.ts
Labels: waiting for review

#1150 feat: add ssh keys and certificates to admin-gui
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-logins/user-settings-logins.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-logins/user-settings-logins.component.scss
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-logins/user-settings-logins.component.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-authentication/service-identity-authentication-overview/service-identity-authentication-overview.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-authentication/service-identity-authentication-overview/service-identity-authentication-overview.component.scss
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-authentication/service-identity-authentication-overview/service-identity-authentication-overview.component.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-authentication/service-identity-authentication.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-authentication/service-identity-authentication.component.scss
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-authentication/service-identity-authentication.component.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-authentication/service-identity-certificates/service-identity-certificates.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-authentication/service-identity-certificates/service-identity-certificates.component.scss
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-authentication/service-identity-certificates/service-identity-certificates.component.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-detail-page/service-identity-overview/service-identity-overview.component.ts
  apps/admin-gui/src/app/users/users-routing.module.ts
  apps/admin-gui/src/app/users/users.module.ts
  apps/admin-gui/src/assets/i18n/en.json
  apps/admin-gui/src/assets/img/PerunWebImages/authentication.svg
  apps/admin-gui/src/assets/img/PerunWebImages/certificates.svg
  apps/admin-gui/src/assets/img/PerunWebImages/key-grey.svg
  apps/admin-gui/src/assets/img/PerunWebImages/key-white.svg
  apps/admin-gui/src/assets/img/PerunWebImages/logins.svg
  apps/user-profile/src/app/app-routing.module.ts
  apps/user-profile/src/app/app.module.ts
  apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.ts
  apps/user-profile/src/app/pages/settings-page/settings-preferred-shells/settings-preferred-shells.component.ts
  apps/user-profile/src/app/pages/settings-page/settings-preferred-unix-group-names/settings-preferred-unix-group-names.component.ts
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
  libs/perun/components/src/index.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/components/src/lib/settings-ssh-keys/settings-ssh-keys.component.html
  libs/perun/components/src/lib/settings-ssh-keys/settings-ssh-keys.component.scss
  libs/perun/components/src/lib/settings-ssh-keys/settings-ssh-keys.component.ts
  libs/perun/dialogs/src/index.ts
  libs/perun/dialogs/src/lib/add-ssh-dialog/add-ssh-dialog.component.html
  libs/perun/dialogs/src/lib/add-ssh-dialog/add-ssh-dialog.component.scss
  libs/perun/dialogs/src/lib/add-ssh-dialog/add-ssh-dialog.component.ts
  libs/perun/dialogs/src/lib/remove-string-value-dialog/remove-string-value-dialog.component.html
  libs/perun/dialogs/src/lib/remove-string-value-dialog/remove-string-value-dialog.component.scss
  libs/perun/dialogs/src/lib/remove-string-value-dialog/remove-string-value-dialog.component.ts
  libs/perun/dialogs/src/lib/show-ssh-dialog/show-ssh-dialog.component.html
  libs/perun/dialogs/src/lib/show-ssh-dialog/show-ssh-dialog.component.scss
  libs/perun/dialogs/src/lib/show-ssh-dialog/show-ssh-dialog.component.ts
  libs/perun/services/src/lib/custom-icon.service.ts
  libs/perun/urns/src/lib/perun-urns.ts
Labels: waiting for review

#1165 feat: better workflow for MFA dialog with MfaRolePrivilegeException
  apps/admin-gui/src/assets/i18n/en.json
  apps/consolidator/src/assets/i18n/en.json
  apps/linker/src/assets/i18n/en.json
  apps/password-reset/src/assets/i18n/cs.json
  apps/password-reset/src/assets/i18n/en.json
  apps/publications/src/assets/i18n/en.json
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
  libs/perun/multi-factor-authentication/src/lib/mfa-required-dialog/mfa-required-dialog.component.html
  libs/perun/multi-factor-authentication/src/lib/mfa-required-dialog/mfa-required-dialog.component.ts
  libs/perun/services/src/lib/ApiInterceptor.ts
  libs/perun/services/src/lib/mfa-handler.service.ts
Labels: waiting for review

#1163 feat(gui): Minimum password length requirements messages added
  apps/admin-gui/src/assets/config/defaultConfig.json
  apps/password-reset/src/assets/config/defaultConfig.json
  apps/user-profile/src/assets/config/defaultConfig.json
Labels: waiting for review

#1164 feat(admin): Manage roles on role-page
  apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-group-role-dialog/add-group-role-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-group-role-dialog/add-group-role-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-group-role-dialog/add-group-role-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-role-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-role-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-role-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-user-role-dialog/add-user-role-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-user-role-dialog/add-user-role-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-user-role-dialog/add-user-role-dialog.component.ts
  apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html
  apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-roles/group-roles.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-roles/group-roles.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/facility-search-select/facility-search-select.component.html
  libs/perun/components/src/lib/facility-search-select/facility-search-select.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/components/src/lib/resource-search-select/resource-search-select.component.html
  libs/perun/components/src/lib/resource-search-select/resource-search-select.component.ts
  libs/perun/components/src/lib/resources-list/resources-list.component.html
  libs/perun/components/src/lib/role-search-select/role-search-select.component.html
  libs/perun/components/src/lib/role-search-select/role-search-select.component.scss
  libs/perun/components/src/lib/role-search-select/role-search-select.component.ts
  libs/perun/components/src/lib/vo-search-select/vo-search-select.component.html
  libs/perun/components/src/lib/vo-search-select/vo-search-select.component.ts
  libs/perun/openapi/src/lib/README.md
  libs/perun/pipes/src/index.ts
  libs/perun/pipes/src/lib/manageable-entities.pipe.ts
  libs/perun/pipes/src/lib/perun-pipes.module.ts
  libs/perun/pipes/src/lib/unassigned-role.pipe.ts
  libs/perun/services/src/lib/gui-auth-resolver.service.ts
  nx.json
Labels: question
