Repository CESNET/perun-web-apps, pull requests merged in 2023-09, with the labels that each got.

#1417 fix(admin): indirect membership
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html
  libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.ts
  libs/perun/dialogs/src/lib/member-tree-view-dialog/member-tree-view-dialog.component.html
  libs/perun/dialogs/src/lib/member-tree-view-dialog/member-tree-view-dialog.component.scss
  libs/perun/pipes/src/index.ts
  libs/perun/pipes/src/lib/member-type-icon.pipe.ts
  libs/perun/pipes/src/lib/member-type-tooltip.pipe.ts
  libs/perun/pipes/src/lib/perun-pipes.module.ts
Labels: waiting for review

#1415 fix(admin): key 'resources' duplicated in localStorage
  apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.html
  libs/perun/models/src/lib/ExpandabelTiles.ts
  libs/perun/services/src/lib/expanded-tiles-store.service.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for review

#1409 fix(profile): navigation working properly in mailing lists settings
  libs/perun/components/src/lib/settings-mailing-lists/mailing-lists.component.ts
Labels: waiting for review

#1416 feat(profile): consolidator config uses full url
  apps/user-profile/src/app/pages/identities-page/identities-page.component.ts
  apps/user-profile/src/assets/config/defaultConfig.json
  libs/perun/models/src/lib/ConfigProperties.ts
Labels: waiting for review

#1406 fix: initialize colors from instance config
  apps/admin-gui/src/_styles.scss
  apps/admin-gui/src/app/app.component.html
  apps/admin-gui/src/app/app.component.ts
  apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts
  apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.scss
  apps/admin-gui/src/assets/config/defaultConfig.json
  apps/consolidator/src/_styles.scss
  apps/linker/src/_styles.scss
  apps/password-reset/src/_styles.scss
  apps/publications/src/_styles.scss
  apps/publications/src/app/services/publications-config.service.ts
  apps/user-profile/src/_styles.scss
  apps/user-profile/src/app/services/user-profile-config.service.ts
  color-migration.js
  libs/config/src/index.ts
  libs/config/src/lib/app-config.service.ts
  package-lock.json
  package.json
Labels: waiting for review, dont merge

#1418 test(admin): fixing the failing E2E tests
  apps/admin-gui-e2e/src/e2e/admin/perun-admin.cy.js
  apps/admin-gui-e2e/src/e2e/facilities/facility-admin.cy.js
  apps/admin-gui-e2e/src/e2e/facilities/facility-observer.cy.js
  apps/admin-gui-e2e/src/e2e/groups/group-admin.cy.js
  apps/admin-gui-e2e/src/e2e/groups/group-observer.cy.js
  apps/admin-gui-e2e/src/e2e/resources/resource-admin.cy.js
  apps/admin-gui-e2e/src/e2e/resources/resource-observer.cy.js
  apps/admin-gui-e2e/src/e2e/resources/resource-self-service.cy.js
  apps/admin-gui-e2e/src/e2e/resources/trusted-facility-admin.cy.js
  apps/admin-gui-e2e/src/e2e/vos/perun-admin.cy.js
  apps/admin-gui-e2e/src/e2e/vos/vo-admin.cy.js
  apps/admin-gui-e2e/src/e2e/vos/vo-observer.cy.js
  apps/admin-gui-e2e/src/support/e2e.ts
Labels: waiting for review

#1412 feat: close session expired dialog in all tabs
  libs/perun/services/src/lib/ApiInterceptor.ts
  libs/perun/services/src/lib/auth.service.ts
Labels: waiting for review

#1427 fix(lib): align items in attribute value list to the left
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.scss
Labels: waiting for review

#1424 feat(profile): allow filtering by name and sorting on profile groups …
  apps/user-profile/src/app/components/membership-list/membership-list.component.html
  apps/user-profile/src/app/pages/groups-page/groups-page.component.html
  apps/user-profile/src/app/pages/groups-page/groups-page.component.ts
  apps/user-profile/src/app/pipes/validate-expiration.pipe.ts
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
Labels: waiting for review

#1425 feat(admin): jump onto specific page
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.css
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.html
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.scss
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
Labels: waiting for review, requested changes

#1421 feat(admin): add bulk operations to applications overview
  apps/admin-gui/src/app/shared/components/application-actions/application-actions.component.html
  apps/admin-gui/src/app/shared/components/application-actions/application-actions.component.scss
  apps/admin-gui/src/app/shared/components/application-actions/application-actions.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/applications-bulk-operation-dialog/applications-bulk-operation-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/applications-bulk-operation-dialog/applications-bulk-operation-dialog.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/applications-bulk-operation-dialog/applications-bulk-operation-dialog.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.ts
  apps/admin-gui/src/app/vos/vos.module.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/application-type-icon/application-type-icon.component.css
  libs/perun/components/src/lib/application-type-icon/application-type-icon.component.html
  libs/perun/components/src/lib/application-type-icon/application-type-icon.component.ts
  libs/perun/components/src/lib/applications-dynamic-list/applications-dynamic-list.component.css
  libs/perun/components/src/lib/applications-dynamic-list/applications-dynamic-list.component.html
  libs/perun/components/src/lib/applications-dynamic-list/applications-dynamic-list.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/dialogs/src/lib/perun-dialogs.module.ts
  libs/perun/openapi/src/lib/.openapi-generator/FILES
  libs/perun/openapi/src/lib/api/groupsManager.service.ts
  libs/perun/openapi/src/lib/api/registrarManager.service.ts
  libs/perun/openapi/src/lib/model/inputSendMessages.ts
  libs/perun/openapi/src/lib/model/models.ts
  libs/perun/pipes/src/index.ts
  libs/perun/pipes/src/lib/application-state.pipe.ts
  libs/perun/pipes/src/lib/perun-pipes.module.ts
Labels: waiting for review

#1430 fix: revert initializing colors during runtime
  apps/admin-gui/src/_styles.scss
  apps/admin-gui/src/app/app.component.html
  apps/admin-gui/src/app/app.component.ts
  apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts
  apps/publications/src/app/services/publications-config.service.ts
  apps/user-profile/src/app/services/user-profile-config.service.ts
  color-migration.js
  libs/config/src/index.ts
  libs/config/src/lib/app-config.service.ts
Labels: waiting for review

#1433 fix(admin): entity text color
  apps/admin-gui/src/_styles.scss
Labels: waiting for review
