Repository CESNET/perun-web-apps, pull requests merged in 2023-05, with the labels that each got.

#1308 fix(admin): fix misaligned ellipsis in sponsored member creation drop…
  apps/admin-gui/src/_styles.scss
Labels: requested changes

#1309 test(admin): refactor structure of e2e tests
  apps/admin-gui-e2e/src/e2e/admin/perun-admin.cy.js
  apps/admin-gui-e2e/src/e2e/admin/perun-observer.cy.js
  apps/admin-gui-e2e/src/e2e/facilities/facility-admin.cy.js
  apps/admin-gui-e2e/src/e2e/facilities/facility-observer.cy.js
  apps/admin-gui-e2e/src/e2e/groups/group-admin.cy.js
  apps/admin-gui-e2e/src/e2e/groups/group-observer.cy.js
  apps/admin-gui-e2e/src/e2e/groups/top-group-creator.cy.js
  apps/admin-gui-e2e/src/e2e/members/membership.cy.js
  apps/admin-gui-e2e/src/e2e/my-profile/self.cy.js
  apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/resources/resource-admin.cy.js
  apps/admin-gui-e2e/src/e2e/resources/resource-observer.cy.js
  apps/admin-gui-e2e/src/e2e/resources/resource-self-service.cy.js
  apps/admin-gui-e2e/src/e2e/resources/trusted-facility-admin.cy.js
  apps/admin-gui-e2e/src/e2e/shared/authentication.cy.js
  apps/admin-gui-e2e/src/e2e/trusted-facility-admin-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/vos/perun-admin.cy.js
  apps/admin-gui-e2e/src/e2e/vos/sponsor.cy.js
  apps/admin-gui-e2e/src/e2e/vos/vo-admin.cy.js
  apps/admin-gui-e2e/src/e2e/vos/vo-observer.cy.js
Labels: waiting for review, dont merge

#1311 build: update eslint config
  .eslintrc.json
  libs/perun/services/src/lib/html-escape.service.ts
Labels: requested changes

#1310 feat(admin): prototype of e2e tests checking for console errors
  apps/admin-gui-e2e/src/e2e/admin/perun-admin.cy.js
  apps/admin-gui-e2e/src/e2e/admin/perun-observer.cy.js
  apps/admin-gui-e2e/src/e2e/facilities/facility-admin.cy.js
  apps/admin-gui-e2e/src/e2e/facilities/facility-observer.cy.js
  apps/admin-gui-e2e/src/e2e/groups/group-admin.cy.js
  apps/admin-gui-e2e/src/e2e/groups/group-observer.cy.js
  apps/admin-gui-e2e/src/e2e/groups/top-group-creator.cy.js
  apps/admin-gui-e2e/src/e2e/resources/resource-admin.cy.js
  apps/admin-gui-e2e/src/e2e/resources/resource-observer.cy.js
  apps/admin-gui-e2e/src/e2e/resources/resource-self-service.cy.js
  apps/admin-gui-e2e/src/e2e/resources/trusted-facility-admin.cy.js
  apps/admin-gui-e2e/src/e2e/vos/perun-admin.cy.js
  apps/admin-gui-e2e/src/e2e/vos/sponsor.cy.js
  apps/admin-gui-e2e/src/e2e/vos/vo-admin.cy.js
  apps/admin-gui-e2e/src/e2e/vos/vo-observer.cy.js
  apps/admin-gui-e2e/src/support/e2e.ts
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
  package-lock.json
  package.json
Labels: waiting for review

#1249 feat: allow inputting multi-line string values to string attributes
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.scss
Labels: waiting for review, dont merge

#1318 fix(lib): do not display bottom pagination in tables
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.html
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
Labels: waiting for review

#1291 feat: use cookies in requests
  apps/admin-gui/src/app/app.module.ts
  apps/consolidator/src/app/app.module.ts
  apps/linker/src/app/app.module.ts
  apps/password-reset/src/app/app.module.ts
  apps/publications/src/app/app.module.ts
  apps/user-profile/src/app/app.module.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for review, dont merge

#1314 feat: handle proxy/local logout and related post logout redirect
  apps/admin-gui/src/app/app-routing.module.ts
  apps/admin-gui/src/assets/config/defaultConfig.json
  apps/admin-gui/src/assets/i18n/en.json
  apps/consolidator/src/app/app-routing.module.ts
  apps/consolidator/src/assets/config/defaultConfig.json
  apps/consolidator/src/assets/i18n/en.json
  apps/password-reset/src/assets/i18n/cs.json
  apps/publications/src/app/app-routing.module.ts
  apps/publications/src/assets/config/defaultConfig.json
  apps/publications/src/assets/i18n/en.json
  apps/user-profile/src/app/app-routing.module.ts
  apps/user-profile/src/assets/config/defaultConfig.json
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
  libs/perun/login/src/lib/login-screen/login-screen.component.html
  libs/perun/login/src/lib/login-screen/login-screen.component.ts
  libs/perun/models/src/lib/ConfigProperties.ts
  libs/perun/services/src/lib/auth.service.ts
  libs/ui/loaders/src/index.ts
  libs/ui/loaders/src/lib/logout-loader/logout-loader.component.html
  libs/ui/loaders/src/lib/logout-loader/logout-loader.component.scss
  libs/ui/loaders/src/lib/logout-loader/logout-loader.component.ts
  libs/ui/loaders/src/lib/ui-loaders.module.ts
Labels: waiting for review

#1319 fix(lib): fix group list icons alignment and margin
  libs/perun/components/src/lib/group-menu/group-menu.component.html
  libs/perun/components/src/lib/group-menu/group-menu.component.scss
Labels: waiting for review

#1317 fix(profile): loading edge cases of Organizations and Groups pages
  apps/user-profile/src/app/components/membership-list/membership-list.component.html
  apps/user-profile/src/app/components/membership-list/membership-list.component.ts
  apps/user-profile/src/app/pages/groups-page/groups-page.component.html
  apps/user-profile/src/app/pages/groups-page/groups-page.component.ts
  apps/user-profile/src/app/pages/vos-page/vos-page.component.html
  apps/user-profile/src/app/pages/vos-page/vos-page.component.ts
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
Labels: waiting for review

#1322 fix(admin): removed immediate filter
  apps/admin-gui/src/app/shared/components/assign-groups-sponsored-members/assign-groups-sponsored-members-component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-role-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/copy-members-dialog/copy-members-dialog-component.html
  apps/admin-gui/src/app/shared/components/dialogs/copy-sponsored-members-dialog/copy-sponsored-members-dialog.component.html
Labels: waiting for review

#1323 fix(admin): disable buttons until the sponsors are not loaded
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.html
  package-lock.json
Labels: waiting for review

#1326 fix(lib): remove white spaces from the full name pipe
  libs/perun/pipes/src/lib/user-full-name.pipe.ts
Labels: waiting for review
