Repository CESNET/perun-web-apps, pull requests merged in 2023-02, with the labels that each got.

#1252 fix(admin): send invitation to one member
  apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.ts
Labels: waiting for review

#1236 fix: fix TODO mdc-migration notes
  apps/admin-gui/src/app/shared/components/dialogs/add-user-ext-source-dialog/add-user-ext-source-dialog.component.scss
  apps/admin-gui/src/styles.scss
  apps/consolidator/src/styles.scss
  apps/user-profile/src/app/pages/settings-page/settings-overview/settings-overview.component.scss
  libs/perun/dialogs/src/lib/add-ssh-dialog/add-ssh-dialog.component.scss
  libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.scss
  libs/perun/dialogs/src/lib/request-change-data-quota-dialog/request-change-data-quota-dialog.component.scss
  libs/perun/namespace-password-form/src/lib/password-form/password-form.component.scss
Labels: waiting for rebase

#1254 fix(admin): fixed a bug that caused an incorrect member to initially …
  apps/admin-gui/src/app/users/pages/user-detail-page/user-accounts/user-accounts.component.ts
Labels: requested changes

#1256 fix(admin): fixed a bug that caused admin user detail page to display…
  apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.ts
Labels: requested changes

#1253 feat: added new method to notificator which manage translation of notification
  libs/perun/services/src/lib/notificator.service.ts
Labels: waiting for review

#1235 feat(apps): remove redundant comments and TODO(v15) comments
  apps/admin-gui/src/styles.scss
  apps/consolidator/src/styles.scss
  apps/linker/src/styles.scss
  apps/password-reset/src/styles.scss
  apps/publications/src/styles.scss
  apps/user-profile/src/styles.scss
Labels: requested changes

#1255 fix(admin): replace mat-selects by our custom search selects
  apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/audit-log-search-select/audit-log-search-select.component.html
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
  libs/perun/components/src/lib/facility-search-select/facility-search-select.component.html
  libs/perun/components/src/lib/facility-search-select/facility-search-select.component.ts
  libs/perun/components/src/lib/resource-search-select/resource-search-select.component.html
  libs/perun/components/src/lib/resource-search-select/resource-search-select.component.ts
Labels: waiting for review

#1247 feat: adjust the mat-button mat-card, mat-checkbox, mat-chips and mat-dialog components after upgrade to angular 15
  apps/admin-gui/src/app/facilities/components/cancel-configuration-dialog/cancel-configuration-dialog.component.html
  apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-facility-owner-dialog/add-facility-owner-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/audit-message-detail-dialog/audit-message-detail-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-edit-service-dialog/create-edit-service-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-facility-dialog/create-facility-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-user-dialog/edit-user-dialog.component.html
  apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.html
  apps/admin-gui/src/app/shared/components/set-login-dialog/set-login-dialog.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html
  apps/admin-gui/src/styles.scss
  apps/consolidator/src/styles.scss
  apps/linker/src/styles.scss
  apps/password-reset/src/styles.scss
  apps/publications/src/app/components/publication-detail-list/publication-detail-list.component.scss
  apps/publications/src/app/components/publication-filter/publication-filter.component.html
  apps/publications/src/app/dialogs/add-authors-dialog/add-authors-dialog.component.html
  apps/publications/src/app/dialogs/show-cite-dialog/show-cite-dialog.component.html
  apps/publications/src/app/pages/create-publication-page/create-publication-page.component.html
  apps/publications/src/app/pages/create-publication-page/create-publication-page.component.scss
  apps/publications/src/app/pages/create-publication-page/import-publications-page/import-publications-page.component.html
  apps/publications/src/app/pages/publication-detail/publication-detail.component.html
  apps/publications/src/styles.scss
  apps/user-profile/src/app/components/dialogs/add-unix-group-dialog/add-unix-group-dialog.component.html
  apps/user-profile/src/styles.scss
  libs/general/src/lib/prevent-proxy-overload-dialog/prevent-proxy-overload-dialog.component.html
  libs/general/src/lib/server-down-dialog/server-down-dialog.component.html
  libs/perun/components/src/lib/advanced-filter/advanced-filter.component.html
  libs/perun/components/src/lib/attribute-search-select/attribute-search-select.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.scss
  libs/perun/components/src/lib/header-menu/header-menu.component.html
  libs/perun/components/src/lib/header-menu/header-menu.component.scss
  libs/perun/components/src/lib/member-overview-groups/member-overview-groups.component.html
  libs/perun/components/src/lib/member-overview-membership/member-overview-membership.component.html
  libs/perun/components/src/lib/refresh-button/refresh-button.component.html
  libs/perun/components/src/lib/refresh-button/refresh-button.component.scss
  libs/perun/dialogs/src/lib/request-change-data-quota-dialog/request-change-data-quota-dialog.component.html
  libs/perun/dialogs/src/lib/show-notification-history-dialog/show-notification-history-dialog.component.html
  libs/perun/dialogs/src/lib/show-ssh-dialog/show-ssh-dialog.component.html
Labels: waiting for review, requested changes

#1257 refactor(admin): use date-range component from Angular material
  apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/date-range/date-range.component.html
  libs/perun/components/src/lib/date-range/date-range.component.ts
Labels: waiting for review

#1261 refactor(admin): move application state selection into separate component
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.ts
  libs/perun/components/src/index.ts
  libs/perun/components/src/lib/application-state-selector/application-state-selector.component.html
  libs/perun/components/src/lib/application-state-selector/application-state-selector.component.scss
  libs/perun/components/src/lib/application-state-selector/application-state-selector.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  package-lock.json
Labels: waiting for review

#1258 feat: Migration to MDC
  apps/admin-gui/src/_styles.scss
  apps/admin-gui/src/app/admin/pages/admin-page/admin-searcher/admin-searcher.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-attributes/facility-attributes.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/audit-message-detail-dialog/audit-message-detail-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-email-footer-dialog/edit-email-footer-dialog.component.html
  apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-accounts/user-accounts.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-attributes/user-attributes.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-bans/user-bans.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-overview/user-overview.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-attributes/group-attributes.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-states/vo-resources-states.component.html
  apps/password-reset/src/_styles.scss
  apps/publications/src/_styles.scss
  apps/publications/src/app/pages/create-publication-page/create-single-publication-page/create-single-publication-page.component.html
  apps/user-profile/src/_styles.scss
  libs/perun/components/src/lib/attribute-rights-tab-group/attribute-rights-tab-group.component.html
  libs/perun/components/src/lib/audit-log-search-select/audit-log-search-select.component.html
  libs/perun/components/src/lib/audit-log-search-select/audit-log-search-select.component.scss
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html
  libs/perun/facility-services-config/src/lib/service-configurator/service-configurator.component.html
  package-lock.json
  package.json
Labels: waiting for review

#1263 ci: follow conventional commits standards to trigger release
  .releaserc.json
  package-lock.json
  package.json
Labels: waiting for review

#1248 feat(admin): user roles are split by source
  apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html
  apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.ts
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/facilities-list/facilities-list.component.html
  libs/perun/components/src/lib/facilities-list/facilities-list.component.ts
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.ts
  libs/perun/components/src/lib/resources-list/resources-list.component.html
  libs/perun/components/src/lib/resources-list/resources-list.component.ts
  libs/perun/components/src/lib/vos-list/vos-list.component.html
  libs/perun/components/src/lib/vos-list/vos-list.component.ts
  libs/perun/openapi/src/lib/api/authzResolver.service.ts
  libs/perun/services/src/lib/role.service.ts
Labels: waiting for review, dont merge

#1262 feat(profile): added option to generate random security text
  apps/user-profile/src/app/components/dialogs/add-auth-text-dialog/add-auth-text-dialog.component.html
  apps/user-profile/src/app/components/dialogs/add-auth-text-dialog/add-auth-text-dialog.component.ts
  apps/user-profile/src/app/components/dialogs/add-auth-text-dialog/words.json
  apps/user-profile/src/assets/i18n/en.json
  apps/user-profile/tsconfig.json
Labels: waiting for review

#1267 fix: minor visual bug fixes after angular 15 migration
  apps/admin-gui/src/_styles.scss
  apps/admin-gui/src/app/admin/pages/admin-page/admin-visualizer/user-destination-relationship/user-destination-relationship.component.html
  apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html
  apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.scss
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.scss
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-service-members/vo-settings-service-members.component.ts
  apps/password-reset/src/_styles.scss
  apps/publications/src/_styles.scss
  apps/user-profile/src/_styles.scss
  apps/user-profile/src/app/pages/profile-page/profile-page.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.scss
  libs/perun/components/src/lib/groups-tree/groups-tree.component.scss
  libs/perun/components/src/lib/member-overview-groups/member-overview-groups.component.html
  libs/perun/components/src/lib/member-overview-membership/member-overview-membership.component.html
Labels: waiting for review

#1272 fix(profile) added missing czech translation for security text genera…
  apps/user-profile/src/assets/i18n/cs.json
Labels: waiting for review

#1266 feat(admin): sponsored member create dialog input fields fix
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/namespace-password-form/src/lib/password-form/password-form.component.ts
Labels: waiting for review
