Repository CESNET/perun-web-apps, pull requests merged in 2023-04, with the labels that each got.

#1290 feat(profile): get MFA categories from entityless attribute instead o…
  apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.ts
  libs/perun/services/src/lib/mfa-api.service.ts
Labels: waiting for review

#1299 fix: temporarily disable html escaping
  libs/perun/services/src/lib/html-escape.service.ts
Labels: waiting for review, dont merge

#1300 fix(admin): fixed bug in expiration-select
  libs/perun/dialogs/src/lib/expiration-select/expiration-select.component.ts
Labels: waiting for review

#1297 fix(admin): services status bulk operations
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.ts
  libs/perun/openapi/src/lib/api/servicesManager.service.ts
Labels: dont merge

#1296 feat: make table headers sticky and tables scrollable
  apps/admin-gui/src/_styles.scss
  apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html
  apps/consolidator/src/_styles.scss
  apps/publications/src/_styles.scss
  apps/user-profile/src/_styles.scss
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.css
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.html
  libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
Labels: waiting for review

#1304 refactor(admin): minor refactoring in the admin pages
  apps/admin-gui/src/app/admin/pages/admin-page/admin-searcher/admin-searcher.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-searcher/admin-searcher.component.ts
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/admin-services.component.ts
Labels: waiting for review

#1305 fix(admin): align icons of Manageable entities on home page with text
  apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-card/dashboard-card.component.html
Labels: waiting for review

#1306 fix(admin): authorization for delete facility
  apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.html
  apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#1301 fix(admin): load ext sources from config file when opening ext source…
  apps/admin-gui/src/app/admin/pages/admin-page/admin-ext-sources/admin-ext-sources.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-ext-sources/admin-ext-sources.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#1307 feat(admin): e2e login command
  apps/admin-gui-e2e/cypress.config.ts
  apps/admin-gui-e2e/src/e2e/facility-management-facility_observer.cy.js
  apps/admin-gui-e2e/src/e2e/facility-management-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/group-management-group_observer.cy.js
  apps/admin-gui-e2e/src/e2e/group-management-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_observer.cy.js
  apps/admin-gui-e2e/src/e2e/resource-management-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/resource-observer-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/resource-self-service-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/sponsor-management-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/top-group-creator-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/trusted-facility-admin-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/vo-management-perun_admin.cy.js
  apps/admin-gui-e2e/src/e2e/vo-observer-perun_admin.cy.js
  apps/admin-gui-e2e/src/index.d.ts
  apps/admin-gui-e2e/src/support/commands.ts
Labels: waiting for review
