Repository CESNET/perun-web-apps, pull requests merged in 2023-07, with the labels that each got.

#1359 fix(admin): refresh group managers
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts
Labels: waiting for review

#1356 fix: don't overlap text in delete dialog
  libs/perun/dialogs/src/lib/delete-entity-dialog/delete-entity-dialog.component.html
  libs/perun/dialogs/src/lib/delete-entity-dialog/delete-entity-dialog.component.scss
Labels: waiting for review

#1360 feat(admin): remove step-up window sign-in page
  apps/admin-gui/src/app/app.component.html
  apps/admin-gui/src/app/app.component.scss
  apps/admin-gui/src/app/app.component.ts
  libs/perun/services/src/lib/mfa-handler.service.ts
Labels: waiting for review

#1358 fix(admin): responsive mfa window
  libs/perun/services/src/lib/mfa-handler.service.ts
Labels: waiting for review

#1354 feat(admin): sponsor this member
  apps/admin-gui/src/app/shared/components/choose-sponsor/choose-sponsor.component.html
  apps/admin-gui/src/app/shared/components/choose-sponsor/choose-sponsor.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/copy-sponsored-members-dialog/copy-sponsored-members-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-this-member-dialog/sponsor-this-member-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-this-member-dialog/sponsor-this-member-dialog.components.html
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-this-member-dialog/sponsor-this-member-dialog.components.scss
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts
  apps/admin-gui/src/assets/i18n/en.json
Labels: waiting for review

#1362 ci: upgrade notes
  .commitlintrc.json
  .github/workflows/check.yml
  .github/workflows/release.yml
  .releaserc.json
  README.md
  package-lock.json
  package.json
Labels: waiting for review

#1369 chore: change commitlint rules
  .commitlintrc.json
  .github/workflows/check.yml
Labels: dont merge

#1368 fix(admin): icon button tooltip
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html
  apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.html
  apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html
  apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-member-sponsors-dialog/edit-member-sponsors-dialog.component.html
  apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-overview/user-overview.component.html
  apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-detail-page/service-identity-detail-page.component.html
  apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.html
  apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.html
  apps/admin-gui/src/assets/i18n/en.json
  apps/consolidator/src/app/components/list-of-identities/list-of-identities.component.html
  apps/consolidator/src/assets/i18n/en.json
  apps/publications/src/app/components/categories-list/categories-list.component.html
  apps/publications/src/assets/i18n/en.json
  apps/user-profile/src/app/pages/profile-page/profile-page.component.html
  apps/user-profile/src/assets/i18n/en.json
  libs/perun/components/src/lib/attribute-rights-collection/attribute-rights-collection.component.html
  libs/perun/components/src/lib/attribute-rights-item/attribute-rights-item.component.html
  libs/perun/components/src/lib/attribute-rights-tab/attribute-rights-tab.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html
  libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.html
  libs/perun/components/src/lib/authorized-groups-cell/authorized-groups-cell.component.html
  libs/perun/components/src/lib/ban-on-entity-list/ban-on-entity-list.component.html
  libs/perun/components/src/lib/group-menu/group-menu.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/groups-tree/groups-tree.component.html
  libs/perun/components/src/lib/membership-status-settings/membership-status-settings.component.html
  libs/perun/components/src/lib/object-list-values/object-list-values.component.html
  libs/perun/components/src/lib/perun-header/perun-header.component.html
  libs/perun/dialogs/src/lib/member-tree-view-dialog/member-tree-view-dialog.component.html
  libs/perun/utils/src/lib/perun-utils.module.ts
  libs/perun/utils/src/lib/table-options/table-options.component.html
Labels: waiting for review, requested changes

#1373 fix(admin): fixed block logins dialog
  apps/admin-gui/src/app/shared/components/dialogs/block-logins-dialog/block-logins-dialog.component.html
Labels: waiting for review

#1366 feat(admin): last successful propagation
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.ts
  apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.html
  apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/openapi/src/lib/model/richDestination.ts
  libs/perun/pipes/src/index.ts
  libs/perun/pipes/src/lib/last-successful-propagation.pipe.ts
  libs/perun/pipes/src/lib/perun-pipes.module.ts
Labels: waiting for review

#1375 fix(lib): hide attributes without values
  libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
Labels: waiting for review
