Repository CESNET/perun-web-apps, pull requests merged in 2023-06, with the labels that each got.

#1328 fix(lib): fix unresponsive layout of perun header
  libs/perun/components/src/lib/header-menu/header-menu.component.html
  libs/perun/components/src/lib/header-menu/header-menu.component.scss
Labels: waiting for review

#1320 fix(admin): application form items i18n correctly displayed
  apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.ts
Labels: requested changes

#1316 fix(admin): disable deselect button
  apps/admin-gui/src/app/admin/pages/admin-page/admin-audit-log/admin-audit-log.component.html
  apps/admin-gui/src/app/admin/pages/admin-page/admin-blocked-logins/admin-blocked-logins.component.html
  apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/applications-list-columns-change-dialog/applications-list-columns-change-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/block-logins-dialog/block-logins-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/notifications-copy-mails-dialog/notifications-copy-mails-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/notifications-copy-mails-dialog/notifications-copy-mails-dialog.component.ts
  libs/perun/components/src/lib/audit-log-search-select/audit-log-search-select.component.html
  libs/perun/components/src/lib/audit-log-search-select/audit-log-search-select.component.ts
  libs/perun/components/src/lib/deselect-button/deselect-button.component.html
  libs/perun/components/src/lib/deselect-button/deselect-button.component.ts
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
  libs/perun/components/src/lib/namespace-search-select/namespace-search-select.component.ts
  libs/perun/components/src/lib/string-search-select/string-search-select.component.html
  libs/perun/components/src/lib/string-search-select/string-search-select.component.ts
Labels: requested changes

#1325 feat(admin): allow managing embedded groups also in a group form settings
  angular.json
  apps/admin-gui/src/app/shared/components/dialogs/add-group-to-group-registration/add-group-to-group-registration.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-group-to-group-registration/add-group-to-group-registration.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/add-group-to-group-registration/add-group-to-group-registration.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-group-to-registration/add-group-to-registration.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-group-to-registration/add-group-to-registration.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/add-group-to-vo-registration/add-group-to-vo-registration.component.html
  apps/admin-gui/src/app/shared/components/dialogs/add-group-to-vo-registration/add-group-to-vo-registration.component.scss
  apps/admin-gui/src/app/shared/components/dialogs/add-group-to-vo-registration/add-group-to-vo-registration.component.ts
  apps/admin-gui/src/app/shared/shared.module.ts
  apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.ts
  apps/admin-gui/src/app/vos/components/application-form-manage-groups/application-form-manage-groups.component.html
  apps/admin-gui/src/app/vos/components/application-form-manage-groups/application-form-manage-groups.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-manage-embedded-groups/group-settings-manage-embedded-groups.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-manage-embedded-groups/group-settings-manage-embedded-groups.component.scss
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-manage-embedded-groups/group-settings-manage-embedded-groups.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-manage-embedded-groups/vo-settings-manage-embedded-groups.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-manage-embedded-groups/vo-settings-manage-embedded-groups.component.scss
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-manage-embedded-groups/vo-settings-manage-embedded-groups.component.ts
  apps/admin-gui/src/app/vos/vos-routing.module.ts
  apps/admin-gui/src/app/vos/vos.module.ts
  libs/perun/openapi/src/lib/api/groupsManager.service.ts
  libs/perun/openapi/src/lib/api/registrarManager.service.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: waiting for review, dont merge

#1329 fix(admin): fix disappearing icons
  apps/admin-gui/src/_styles.scss
Labels: waiting for review

#1330 fix: do not show sesssion expiration dialog during mfa
  libs/perun/services/src/lib/ApiInterceptor.ts
Labels: waiting for review

#1335 fix(admin): disable remove button
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.html
Labels: waiting for review

#1334 fix(admin): disable auto select of vo
  apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.html
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/vo-search-select/vo-search-select.component.html
  libs/perun/components/src/lib/vo-search-select/vo-search-select.component.ts
Labels: waiting for review

#1336 fix(admin): add host dialog fixed
  apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.ts
Labels: waiting for review

#1327 fix(admin): fix login screen service access component
  libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.html
  libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.ts
  libs/perun/services/src/lib/auth.service.ts
  libs/perun/services/src/lib/init-auth.service.ts
Labels: waiting for review

#1338 fix(lib): handle MfaRoleTimeoutException
  libs/perun/services/src/lib/ApiInterceptor.ts
  libs/perun/services/src/lib/mfa-handler.service.ts
Labels: dont merge

#1339 fix: add new defaul acr value
  apps/admin-gui/src/assets/config/defaultConfig.json
  apps/consolidator/src/assets/config/defaultConfig.json
  apps/linker/src/assets/config/defaultConfig.json
  apps/password-reset/src/assets/config/defaultConfig.json
  apps/publications/src/assets/config/defaultConfig.json
  apps/user-profile/src/assets/config/defaultConfig.json
  libs/perun/models/src/lib/ConfigProperties.ts
  libs/perun/services/src/lib/auth.service.ts
Labels: waiting for review

#1340 fix(profile): Remove ellipses from save mfa button
  apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.html
Labels: waiting for review

#1345 fix(admin): remove icons on roles overview page
  apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html
Labels: waiting for review

#1347 fix(admin): unify color of mat-slide-toggles
  apps/admin-gui/src/app/shared/components/settings-toggle-item/settings-toggle-item.component.html
  apps/admin-gui/src/app/vos/components/expiration-settings/expiration-settings.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html
  libs/perun/components/src/lib/attribute-critical-operations-toggles/attribute-critical-operations-toggles.component.html
  libs/perun/components/src/lib/attribute-unique-toggle/attribute-unique-toggle.component.html
Labels: waiting for review

#1348 fix(admin): transparent scrollbar
  apps/admin-gui/src/app/app.component.scss
Labels: waiting for review

#1346 fix(admin): adjusted spacing between toggles
  apps/admin-gui/src/_styles.scss
  apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html
  libs/perun/components/src/lib/attribute-critical-operations-toggles/attribute-critical-operations-toggles.component.html
Labels: waiting for review

#1350 feat(admin): add feedback on hover to member status
  apps/admin-gui/src/_styles.scss
  libs/perun/components/src/lib/group-resource-status/group-resource-status.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html
  libs/perun/components/src/lib/members-list/members-list.component.html
Labels: waiting for review

#1351 fix: add background to active tab
  apps/admin-gui/src/_styles.scss
  apps/password-reset/src/_styles.scss
  apps/publications/src/_styles.scss
  apps/user-profile/src/_styles.scss
Labels: waiting for review

#1331 fix: Unify member status and expiration change
  apps/admin-gui/src/app/shared/components/dialogs/copy-sponsored-members-dialog/copy-sponsored-members-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/copy-sponsored-members-dialog/copy-sponsored-members-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/change-member-status-or-expiration-dialog/change-member-status-or-expiration-dialog.component.html
  libs/perun/components/src/lib/change-member-status-or-expiration-dialog/change-member-status-or-expiration-dialog.component.ts
  libs/perun/components/src/lib/member-overview-groups/member-overview-groups.component.html
  libs/perun/components/src/lib/member-overview-groups/member-overview-groups.component.ts
  libs/perun/components/src/lib/member-overview-membership/member-overview-membership.component.html
  libs/perun/components/src/lib/member-overview-membership/member-overview-membership.component.ts
  libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.ts
  libs/perun/components/src/lib/membership-status-settings/membership-status-settings.component.html
  libs/perun/components/src/lib/membership-status-settings/membership-status-settings.component.scss
  libs/perun/components/src/lib/membership-status-settings/membership-status-settings.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.html
  libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.ts
  libs/perun/dialogs/src/lib/change-group-expiration-dialog/change-group-expiration-dialog.component.html
  libs/perun/dialogs/src/lib/change-group-expiration-dialog/change-group-expiration-dialog.component.ts
  libs/perun/dialogs/src/lib/change-member-status-dialog/change-member-status-dialog.component.html
  libs/perun/dialogs/src/lib/change-member-status-dialog/change-member-status-dialog.component.ts
  libs/perun/dialogs/src/lib/change-sponsorship-expiration-dialog/change-sponsorship-expiration-dialog.component.html
  libs/perun/dialogs/src/lib/change-vo-expiration-dialog/change-vo-expiration-dialog.component.html
  libs/perun/dialogs/src/lib/change-vo-expiration-dialog/change-vo-expiration-dialog.component.ts
  libs/perun/dialogs/src/lib/expiration-select/expiration-select.component.html
  libs/perun/dialogs/src/lib/expiration-select/expiration-select.component.ts
  libs/perun/pipes/src/lib/group-status-icon-color.ts
  libs/perun/pipes/src/lib/member-status-icon-color.pipe.ts
Labels: waiting for review
