Repository CESNET/perun-web-apps, pull requests merged in 2023-03, with the labels that each got.

#1271 fix: bug fixes after angular 15 migration
  apps/publications/src/app/services/publications-config.service.ts
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
Labels: waiting for review

#1270 fix: bug fixes after angular 15 migration
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.html
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.ts
  apps/admin-gui/src/app/vos/pages/member-detail-page/member-bans/member-bans.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-hierarchical-inclusion/vo-settings-hierarchical-inclusion.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-member-organizations/add-member-organization-dialog/add-member-organization-dialog.component.html
Labels: waiting for review

#1269 fix: minor visual bug fixes after angular 15 migration
  apps/admin-gui/src/_styles.scss
  apps/consolidator/src/assets/config/defaultConfig.json
  apps/linker/src/assets/config/defaultConfig.json
  apps/password-reset/src/_styles.scss
  apps/password-reset/src/assets/config/defaultConfig.json
  apps/publications/src/_styles.scss
  apps/user-profile/src/_styles.scss
  apps/user-profile/src/app/pages/settings-page/settings-samba-password/settings-samba-password.component.html
  apps/user-profile/src/app/pages/settings-page/settings-samba-password/settings-samba-password.component.scss
  libs/perun/components/src/lib/settings-mailing-lists/mailing-lists.component.html
Labels: waiting for review

#1265 fix(profile): login page is correctly displayed after session expiration
  apps/admin-gui/src/app/app.component.html
  apps/admin-gui/src/app/app.component.ts
  apps/user-profile/src/app/app.component.html
  apps/user-profile/src/app/app.component.ts
  libs/perun/services/src/lib/ApiInterceptor.ts
Labels: waiting for review

#1273 feat(admin): extended the authorized group column in roles page list
  apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/authorized-groups-cell/authorized-groups-cell.component.html
  libs/perun/components/src/lib/authorized-groups-cell/authorized-groups-cell.component.scss
  libs/perun/components/src/lib/authorized-groups-cell/authorized-groups-cell.component.ts
  libs/perun/components/src/lib/facilities-list/facilities-list.component.html
  libs/perun/components/src/lib/groups-list/groups-list.component.html
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/components/src/lib/resources-list/resources-list.component.html
  libs/perun/components/src/lib/vos-list/vos-list.component.html
  libs/perun/components/src/lib/vos-list/vos-list.component.ts
Labels: waiting for review

#1280 fix: browser history for change password dialog
  libs/perun/components/src/lib/password-reset/password-reset.component.ts
Labels: waiting for review

#1276 fix(admin): fixed a bug where consent status column would not display…
  apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.html
  libs/perun/components/src/lib/users-dynamic-list/users-dynamic-list.component.ts
Labels: waiting for review

#1283 feat(profile): remove the option to add admin ssh key
  apps/admin-gui/src/assets/i18n/en.json
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
  libs/perun/components/src/lib/settings-ssh-keys/settings-ssh-keys.component.html
  libs/perun/components/src/lib/settings-ssh-keys/settings-ssh-keys.component.ts
Labels: requested changes

#1285 fix: fixed bug that caused overlay components to block gui
  apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts
Labels: waiting for review

#1274 feat(admin): Change member status with expiration
  .gitignore
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/index.ts
  libs/perun/components/src/lib/expiration-select/expiration-select.component.ts
  libs/perun/components/src/lib/member-overview-groups/member-overview-groups.component.ts
  libs/perun/components/src/lib/member-overview-membership/member-overview-membership.component.html
  libs/perun/components/src/lib/member-overview-membership/member-overview-membership.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/dialogs/src/lib/change-group-expiration-dialog/change-group-expiration-dialog.component.ts
  libs/perun/dialogs/src/lib/change-member-status-dialog/change-member-status-dialog.component.html
  libs/perun/dialogs/src/lib/change-member-status-dialog/change-member-status-dialog.component.ts
  libs/perun/dialogs/src/lib/change-vo-expiration-dialog/change-vo-expiration-dialog.component.ts
  libs/perun/dialogs/src/lib/expiration-select/expiration-select.component.css
  libs/perun/dialogs/src/lib/expiration-select/expiration-select.component.html
  libs/perun/dialogs/src/lib/expiration-select/expiration-select.component.ts
  libs/perun/dialogs/src/lib/perun-dialogs.module.ts
  libs/perun/pipes/src/lib/member-status.pipe.ts
  libs/perun/pipes/src/lib/transform-member-status.pipe.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for review

#1288 fix(profile): add a meaningful error message when call to MFA API fails.
  apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.html
  apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.ts
  apps/user-profile/src/assets/i18n/cs.json
  apps/user-profile/src/assets/i18n/en.json
Labels: waiting for review

#1238 fix(admin): correctly parse fedInfo in applications, show display names
  apps/admin-gui/src/app/shared/components/dialogs/applications-list-columns-change-dialog/applications-list-columns-change-dialog.component.html
  apps/admin-gui/src/app/shared/components/dialogs/applications-list-columns-change-dialog/applications-list-columns-change-dialog.component.ts
  apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.html
  apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.ts
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.html
  apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.ts
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.html
  apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.ts
  apps/admin-gui/src/assets/i18n/en.json
  libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
  libs/perun/components/src/lib/perun-components.module.ts
  libs/perun/components/src/lib/string-search-select/string-search-select.component.html
  libs/perun/components/src/lib/string-search-select/string-search-select.component.scss
  libs/perun/components/src/lib/string-search-select/string-search-select.component.ts
  libs/perun/utils/src/lib/perun-utils.ts
Labels: waiting for rebase
